// ملف مستقل تماماً يحتوي فقط على الأسئلة: arch-data.js
const QUESTIONS = [
    {
        id: 1,
        type: "mcq",
        q: "MAR is an abbreviation of:",
        opts: [
            "Minimum Acceptable Rate",
            "Magnetic Resonance Angiography",
            "Memory Accumulator Register",
            "Memory Address Register",
        ],
        ans: 3,
    },
    {
        id: 2,
        type: "mcq",
        q: "CU is an abbreviation of:",
        opts: ["Copper Unit", "Control Unit", "Central Unit", "Core Unit"],
        ans: 1,
    },
    {
        id: 3,
        type: "mcq",
        q: "MBR is an abbreviation of:",
        opts: [
            "Master Boot Record",
            "Memory Built Register.",
            "Memory Buffer Register.",
            "Memory Bus Register.",
        ],
        ans: 2,
    },
    {
        id: 4,
        type: "mcq",
        q: "IR is an abbreviation of:",
        opts: [
            "Infrared",
            "Installation Register",
            "Insertion Register",
            "Instruction Register",
        ],
        ans: 3,
    },
    {
        id: 5,
        type: "mcq",
        q: "DMA is an abbreviation of:",
        opts: [
            "Defense Media Activity",
            "Direct Memory Access",
            "Direct Memory Addition",
            "Direct Method Access",
        ],
        ans: 1,
    },
    {
        id: 6,
        type: "mcq",
        q: "CPI is an abbreviation of:",
        opts: [
            "Cycles per Insertion",
            "Cycles per Instruction",
            "Clock per Insertion",
            "Clock per Instruction.",
        ],
        ans: 1,
    },
    {
        id: 7,
        type: "mcq",
        q: "ISR is an abbreviation of:",
        opts: [
            "Interrupt Security Routine.",
            "Interrupt Service Region.",
            "Interrupt Service Routine.",
            "Interrupt Service Rescue.",
        ],
        ans: 2,
    },
    {
        id: 8,
        type: "mcq",
        q: "ICC is an abbreviation of:",
        opts: [
            "Instruction clock code",
            "Instruction cycle core",
            "Instruction clock core",
            "Instruction cycle code",
        ],
        ans: 3,
    },
    {
        id: 9,
        type: "mcq",
        q: "The component which controls the operation of the computer is:",
        opts: ["MAR", "ALU", "CPU", "GPU"],
        ans: 2,
    },
    {
        id: 10,
        type: "mcq",
        q: "Where are the registers located in the computer top level structure:",
        opts: ["CPU", "ALU", "CU", "GPU"],
        ans: 0,
    },
    {
        id: 11,
        type: "tf",
        q: "Decoding function is responsible for storing the decoded instruction.",
        ans: false,
    },
    {
        id: 12,
        type: "mcq",
        q: "Employed to hold temporarily operands and results of ALU operations we cannot give any results without dealing with the Accumulator first.",
        opts: ["MAR", "MBR", "AC", "IR"],
        ans: 2,
    },
    {
        id: 13,
        type: "mcq",
        q: "Specifies the address in memory to be written from or read into the MBR.",
        opts: ["MAR", "PC", "AC", "IR"],
        ans: 0,
    },
    {
        id: 14,
        type: "mcq",
        q: "Contains Data or Instructions to be sent or received from or to the I/O registers or the IR if it was the instruction.",
        opts: ["MAR", "MBR", "AC", "PC"],
        ans: 1,
    },
    {
        id: 15,
        type: "mcq",
        q: "Contains the instruction delivered to be decoded by the control unit.",
        opts: ["MAR", "MBR", "IR", "PC"],
        ans: 2,
    },
    {
        id: 16,
        type: "mcq",
        q: "Contains the address of the next instruction to be fetched from memory.",
        opts: ["MAR", "MBR", "AC", "PC"],
        ans: 3,
    },
    {
        id: 17,
        type: "mcq",
        q: "contain the address of the input/output device.",
        opts: ["MAR", "MBR", "I/O AR", "I/O BR"],
        ans: 2,
    },
    {
        id: 18,
        type: "mcq",
        q: "contain the data to be transferred from/to the input/output device.",
        opts: ["MAR", "MBR", "I/O AR", "I/O BR"],
        ans: 3,
    },
    {
        id: 19,
        type: "tf",
        q: "all computer functions are data processing, data storage and data movement.",
        ans: false,
    },
    {
        id: 20,
        type: "mcq",
        q: "In the instruction cycle state diagram instruction operation decoding is followed by:",
        opts: [
            "Operand Fetch",
            "Operand Store",
            "Operand Address Calculation",
            "Data Operation",
        ],
        ans: 2,
    },
    {
        id: 21,
        type: "mcq",
        q: "In the instruction cycle state diagram data operation is perceived by",
        opts: [
            "Operand Fetch",
            "Operand Store",
            "Operand Address Calculation",
            "Data Operation",
        ],
        ans: 2,
    },
    {
        id: 22,
        type: "tf",
        q: "In the instruction cycle state diagram Instruction address calculation performed after instruction fetch.",
        ans: false,
    },
    {
        id: 23,
        type: "mcq",
        q: "In the instruction cycle state diagram, which of the following is the right sequence:",
        opts: [
            "Instruction address calculation, instruction operation decoding, instruction fetch.",
            "instruction fetch, Instruction address calculation, instruction operation decoding.",
            "Instruction address calculation, instruction fetch, instruction operation decoding.",
            "instruction operation decoding, instruction fetch, Instruction address calculation.",
        ],
        ans: 2,
    },
    {
        id: 24,
        type: "mcq",
        q: "In the instruction cycle state diagram, which of the following is the right sequence:",
        opts: [
            "data operation, operand fetch, Operand address calculation.",
            "Operand address calculation, data operation, operand fetch.",
            "Operand fetch, Operand address calculation, data operation.",
            "Operand address calculation, operand fetch, data operation.",
        ],
        ans: 3,
    },
    {
        id: 25,
        type: "mcq",
        q: "Machine A runs a program in 20 seconds, machine B runs the same program in 25 seconds. how many times faster is machine A.",
        opts: ["1.5", "1.25", "1.75", "2"],
        ans: 1,
    },
    {
        id: 26,
        type: "mcq",
        q: "Machine A runs a program in 25 seconds, machine B runs the same program in 65 seconds. how many times faster is machine A.",
        opts: ["2.5", "2.6", "2.9", "2.4"],
        ans: 1,
    },
    {
        id: 27,
        type: "mcq",
        q: "Machine A runs a program in 20 seconds, machine B runs the same program. Machine A is three times faster than machine B. How many seconds does machine B takes to run this program.",
        opts: ["90 Seconds", "60 Seconds", "80 Seconds", "70 Seconds"],
        ans: 1,
    },
    {
        id: 28,
        type: "mcq",
        q: "Machine A runs a program in 40 seconds, machine B runs the same program in 70 seconds. how many times slower is machine B.",
        opts: ["1.25", "1.5", "1.75", "2"],
        ans: 2,
    },
    {
        id: 29,
        type: "mcq",
        q: "Machine A runs a program in 25 seconds, machine B runs the same program in 65 seconds. how many times slower is machine B.",
        opts: ["2.5", "2.6", "2.9", "2.4"],
        ans: 1,
    },
    {
        id: 30,
        type: "mcq",
        q: "Machine A runs a program in 20 seconds. Machine B is three times slower than machine A. how many seconds does machine B takes to run this program.",
        opts: ["90 Seconds", "60 Seconds", "80 Seconds", "70 Seconds"],
        ans: 1,
    },
    {
        id: 31,
        type: "mcq",
        q: "Calculate the number of clock cycle of a program execution that contain: 24 mov instruction which are executed in a 3 clock cycle. 11 add instruction which are executed in 5 clock cycle, Loop which repeated 5 times and has 4 mov and 3 add instructions.",
        opts: [
            "252 clock cycle",
            "332 clock cycle",
            "262 clock cycle",
            "391 clock cycle",
        ],
        ans: 2,
    },
    {
        id: 32,
        type: "mcq",
        q: "a program executes in 1200 clock cycle and runs in 25 seconds. Calculate the clock rate.",
        opts: ["4.8 HZ", "3000 HZ", "300 HZ", "48 HZ"],
        ans: 3,
    },
    {
        id: 33,
        type: "mcq",
        q: "a program executes in 3000 clock cycle and runs in 50 seconds. Calculate the clock rate.",
        opts: ["150000 HZ", "60 HZ", "600 HZ", "15000 HZ"],
        ans: 1,
    },
    {
        id: 34,
        type: "mcq",
        q: "A program has a clock rate of 60HZ and runs in 20 seconds. Calculate the number of clock cycles.",
        opts: [
            "3 clock cycle",
            "12 clock cycle",
            "1200 clock cycle",
            "300 clock cycle",
        ],
        ans: 2,
    },
    {
        id: 35,
        type: "mcq",
        q: "a program has a clock rate of 50HZ and runs in 30 seconds. Calculate the number of clock cycles.",
        opts: [
            "150 clock cycle",
            "1500 clock cycle",
            "15 clock cycle",
            "1.5 clock cycle",
        ],
        ans: 1,
    },
    {
        id: 36,
        type: "mcq",
        q: "a program executes in 700 clock cycle and a clock rate of 14 HZ. Calculate the time needed to run this program.",
        opts: ["25 second", "50 second", "70 second", "60 second"],
        ans: 1,
    },
    {
        id: 37,
        type: "mcq",
        q: "a program executes in 2000 clock cycle and a clock rate of 80 HZ. Calculate the time needed to run this program.",
        opts: ["25 second", "50 second", "70 second", "60 second"],
        ans: 0,
    },
    {
        id: 38,
        type: "mcq",
        q: "structure: the way in which the components are:",
        opts: [
            "communicated",
            "interrelated",
            "connected",
            "All other choices",
        ],
        ans: 1,
    },
    {
        id: 39,
        type: "mcq",
        q: "function is the operation of each individual component as part of:",
        opts: [
            "the communications system",
            "the system",
            "the structure",
            "All other choices",
        ],
        ans: 2,
    },
    {
        id: 40,
        type: "mcq",
        q: "the internal bus interconnects:",
        opts: [
            "CPU and input/output module",
            "CU and registers only",
            "CU, registers, and ALU",
        ],
        ans: 2,
    },
    {
        id: 41,
        type: "mcq",
        q: "nested interrupts Occurs when:",
        opts: [
            "one interrupt is executed after finishing of execution of another interrupt",
            "one interrupt calls another interrupt while executing the 1st one",
            "two interrupts are called instantaneously at the same time.",
            "All other choices",
        ],
        ans: 1,
    },
    {
        id: 42,
        type: "mcq",
        q: "sequential interrupts Occurs when:",
        opts: [
            "one interrupt is executed after finishing of execution of another interrupt.",
            "All other choices",
            "one interrupt calls another interrupt while executing the 1st one.",
            "Two interrupts are called instantaneously",
        ],
        ans: 0,
    },
    {
        id: 43,
        type: "mcq",
        q: "if a program starts at time zero and after some time, it has printer and plotter interrupts (at same time) which will execute in 25 μs for each of them. after 10μs of the start of printer interrupt it has a communication interrupt which will remain 25μs. the printer and communication interrupts are:",
        opts: [
            "Nested interrupt",
            "Nested interrupt and sequential interrupt",
            "none of the other choices",
            "sequential interrupt",
        ],
        ans: 0,
    },
    {
        id: 44,
        type: "mcq",
        q: "if a program starts at time zero and after some time, it has printer and plotter interrupts (at same time) which will execute in 25 μs for each of them. after 10μs of the start of printer interrupt it has a communication interrupt which will remain 25μs assuming high priority for printer interrupt, the printer and plotter interrupts could be considered as:",
        opts: [
            "Nested interrupt",
            "Nested interrupt and sequential interrupt",
            "none of the other choices",
            "sequential interrupt",
        ],
        ans: 3,
    },
    {
        id: 45,
        type: "mcq",
        q: "Which of the following registers is used in interrupt cycle:",
        opts: [
            "IR, MAR, MBR",
            "MAR, AC, MBR",
            "MAR, MBR, PC",
            "MAR, MBR, IR, PC",
        ],
        ans: 2,
    },
    {
        id: 46,
        type: "mcq",
        q: "how much time does the interrupt cycle take:",
        opts: ["3", "4", "5", "6"],
        ans: 0,
    },
    {
        id: 47,
        type: "mcq",
        q: "how much time does the indirect cycle take:",
        opts: ["3", "4", "5", "6"],
        ans: 3,
    },
    {
        id: 48,
        type: "mcq",
        q: "Calculate the number of clock cycle of a program execution that contain: 24 mov instruction which are executed in a 2 clock cycle. 11 add instruction which are executed in 4 clock cycle, Loop which repeated 8 times and has 4 mov and 3 add instructions.",
        opts: [
            "252 clock cycle",
            "332 clock cycle",
            "262 clock cycle",
            "391 clock cycle",
        ],
        ans: 0,
    },
    {
        id: 49,
        type: "mcq",
        q: "Calculate the number of clock cycle of a program execution that contain: 27 mov instructions which are executed in a 3 clock cycle. 11 add instruction which are executed in 5 clock cycle, Loop which repeated 5 times and has 7 mov and 6 add instructions.",
        opts: [
            "252 clock cycle",
            "332 clock cycle",
            "262 clock cycle",
            "391 clock cycle",
        ],
        ans: 3,
    },
    {
        id: 50,
        type: "mcq",
        q: "Calculate the number of clock cycle of a program execution that contain: 24 mov instruction which are executed in a 3 clock cycle. 15 add instruction which are executed in 5 clock cycle, Loop which repeated 5 times and has 4 mov and 5 add instructions.",
        opts: [
            "252 clock cycle",
            "332 clock cycle",
            "262 clock cycle",
            "282 clock cycle",
        ],
        ans: 1,
    },
    {
        id: 51,
        type: "mcq",
        q: "Registers provides:",
        opts: [
            "computer’s data processing functions inside CPU",
            "controls for operation of the CPU and hance the computer",
            "internal storage to the CPU",
            "All other Choices",
        ],
        ans: 2,
    },
    {
        id: 52,
        type: "mcq",
        q: "some components inside CPU:",
        opts: [
            "Program Counter (PC)",
            "Memory Address Register (MAR)",
            "Memory Buffer Register (MBR)",
            "All other Choices",
        ],
        ans: 3,
    },
    {
        id: 53,
        type: "mcq",
        q: "input /output module is located:",
        opts: [
            "outside CPU",
            "inside CPU",
            "inside the memory",
            "All of other choices",
        ],
        ans: 0,
    },
    {
        id: 54,
        type: "mcq",
        q: "Task of control unit",
        opts: [
            "Micro-instruction sequencing and Micro-instruction execution.",
            "Micro-instruction sequencing only",
            "Micro-instruction execution only",
            "None of the other choices",
        ],
        ans: 0,
    },
    {
        id: 55,
        type: "mcq",
        q: "Types of interrupts are:",
        opts: ["Timer, I/O", "hardware failure", "Program", "All the above"],
        ans: 3,
    },
    {
        id: 56,
        type: "mcq",
        q: "when does the program interrupt happen:",
        opts: [
            "illegal instructions",
            "arithmetic overflow",
            "divide by zero, memory handling error.",
            "All the above",
        ],
        ans: 3,
    },
    {
        id: 57,
        type: "mcq",
        q: "I/O interrupt is Generated by an I/O controller to request service from the processor except:",
        opts: ["keyboard, mouse.", "disk drive.", "NIC.", "Timer"],
        ans: 3,
    },
    {
        id: 58,
        type: "mcq",
        q: "signifies some error condition with the hardware.",
        opts: ["Program", "Timer", "I/O", "hardware failure"],
        ans: 3,
    },
    {
        id: 59,
        type: "mcq",
        q: "The Check for interrupt begins……",
        opts: [
            "After fetching the instruction",
            "Before the execution of the current instruction",
            "After the execution of the current instruction",
            "Before fetching the instruction",
        ],
        ans: 2,
    },
    {
        id: 60,
        type: "mcq",
        q: "The size of any register is …",
        opts: [
            "16 bits",
            "According to the memory",
            "according to microprocessor",
            "32 bits",
        ],
        ans: 2,
    },
    {
        id: 61,
        type: "mcq",
        q: "All of the following are steps in the fetch cycle except:",
        opts: [
            "Program Counter (PC) holds the address of next instruction to fetch.",
            "The processor fetches instruction from memory location pointed to by PC.",
            "decrement PC unless instructed otherwise.",
            "Instruction loaded into Instruction Register (IR)",
        ],
        ans: 2,
    },
];
