const QUESTIONS = [
    {
        id: 1,
        type: "mcq",
        q: "In symmetric encryption",
        opts: [
            "We have a key for encryption and another for decryption",
            "The encryption and decryption are done with one key",
            "Different keys are used for encryption",
        ],
        ans: 1,
        why: "المحاضرة 5: التشفير المتماثل (Symmetric encryption) يعتمد على استخدام مفتاح واحد مشترك (One key) لإجراء كل من عمليتي التشفير وفك التشفير.",
    },
    {
        id: 2,
        type: "mcq",
        q: "DES encryption starts with",
        opts: ["Permutation", "Substitution", "Confusion"],
        ans: 0,
        why: "المحاضرة 3: تبدأ خوارزمية DES لتشفير الكتل بتمرير النص في دالة التبديل الأولي (Initial Permutation).",
    },
    {
        id: 3,
        type: "mcq",
        q: "To apply Digital signature to a message",
        opts: [
            "Encrypt the message with the private key of the sender.",
            "Encrypt the message with the public key of sender.",
            "Encrypt the message with private key of recipient.",
        ],
        ans: 0,
        why: "المحاضرة 5 والمحاضرة 7: لإنشاء توقيع رقمي (Digital Signature)، يجب على المرسل تشفير الرسالة (أو قيمة التجزئة الخاصة بها) باستخدام مفتاحه الخاص (Sender's private key).",
    },
    {
        id: 4,
        type: "mcq",
        q: "To assure the sender personality when sending message from node A to node B",
        opts: [
            "Encrypt the message with private key of B",
            "Encrypt the message with public key of A",
            "Encrypt the message with private key of A",
        ],
        ans: 2,
        why: "المحاضرة 5: لضمان هوية المرسل (المصادقة - Authentication)، تقوم العقدة A بتشفير الرسالة باستخدام مفتاحها الخاص (Private key of A) بحيث يتأكد المستقبل من هويتها.",
    },
    {
        id: 5,
        type: "mcq",
        q: "In PGP, to achieve authentication the hash code of sender message encrypted with",
        opts: [
            "Sender private key",
            "Sender public key",
            "Receiver private key",
        ],
        ans: 0,
        why: "المحاضرة 7: في بروتوكول PGP لتحقيق المصادقة (Authentication)، يتم تشفير كود التجزئة (Hash) للرسالة باستخدام المفتاح الخاص للمرسل (Sender private key).",
    },
    {
        id: 6,
        type: "mcq",
        q: "The KDC creates secret key for each member to be used between",
        opts: ["the member and the KDC.", "two members.", "One member."],
        ans: 0,
        why: "المحاضرة 1: مركز توزيع المفاتيح (KDC) يقوم بإنشاء مفتاح سري رئيسي يشارك بين العضو والمركز نفسه (the member and the KDC) لتسهيل إدارة وتوزيع المفاتيح.",
    },
    {
        id: 7,
        type: "mcq",
        q: "To send message to node N securely over wireless network",
        opts: [
            "Encrypt the message with public key of node N",
            "Encrypt the message with private key of node N",
            "Encrypt the message with hash encryption",
        ],
        ans: 0,
        why: "المحاضرة 5: لإرسال رسالة بسرية تامة (Confidentiality)، يتم تشفيرها باستخدام المفتاح العام للمستقبل (Public key of node N) بحيث لا يفك تشفيرها سوى مفتاحه الخاص.",
    },
    {
        id: 8,
        type: "mcq",
        q: "In S-DES a 10-bit key is initialized for each",
        opts: ["Block", "Round", "Message"],
        ans: 0,
        why: "المحاضرة 3 و 6: خوارزمية S-DES (وكذلك DES) هي خوارزمية تشفير كتلي (Block Cipher)، بالتالي يتم تهيئة المفتاح الأساسي ليُطبق على كل كتلة (Block) من البيانات.",
        action: "تنبيه هام: السؤال التالي اجابته تختلف عن الاجابة في جروب السيريال, اجابة جروب السيريال هى [Round]. و التحليل الظاهر هو تحليل لاجابة الموقع",
    },
    {
        id: 9,
        type: "mcq",
        q: "When attacker makes part of system unavailable this threat is considered",
        opts: ["Active threat", "Interruption threat", "Interception threat"],
        ans: 1,
        why: "المحاضرة 1: التهديد الذي يجعل جزءاً من النظام غير متاح يُعرف بتهديد الانقطاع (Interruption threat) وهو يستهدف تعطيل خدمة التوافر (Availability) ويعتبر هجوماً نشطاً كحجب الخدمة (DoS).",
    },
    {
        id: 10,
        type: "mcq",
        q: "Something of value which has to be protected. It is",
        opts: ["Asset", "Threat", "Vulnerability"],
        ans: 0,
        why: "المحاضرة 1: ضمن المفاهيم الأمنية الأساسية، الأصل (Asset) هو أي مورد أو شيء ذو قيمة تملكه المؤسسة ويجب حمايته من المخاطر.",
    },
    {
        id: 11,
        type: "mcq",
        q: "Applying hash function to different messages size leads to",
        opts: [
            "Similar hash values",
            "Similar size of hash",
            "large message size",
        ],
        ans: 1,
        why: "المحاضرة 1: الوظيفة الأساسية لدالة التجزئة (Hash) هي أخذ رسائل بأحجام مختلفة وضغطها لتنتج مخرجات ذات طول وحجم ثابت (Similar size of hash).",
    },
    {
        id: 12,
        type: "mcq",
        q: "Modification threat is concerned with",
        opts: ["Data confidentiality", "Data integrity", "Data availability"],
        ans: 1,
        why: "المحاضرة 1: تهديد التعديل (Modification) يستهدف الإخلال بسلامة ونزاهة البيانات (Data integrity) وتغيير محتواها بطريقة غير مصرح بها.",
    },
    {
        id: 13,
        type: "tf",
        q: "To generate the key of simplified DES, the 10-bit key is transformed into two 8-bit sub-keys K1 and K2.",
        ans: true,
        why: "المحاضرة 3: خوارزمية S-DES تأخذ مفتاحاً أساسياً بحجم 10 بت وتجري عليه عمليات تحويل لتوليد مفتاحين فرعيين بحجم 8 بت لكل جولة (K1 و K2).",
    },
    {
        id: 14,
        type: "tf",
        q: "Playfair cipher encrypt pairs of letters instate of single letter.",
        ans: true,
        why: "المحاضرة 2: شفرة Playfair تعتمد على تشفير أزواج من الأحرف (Pairs of letters) بدلاً من حرف واحد لزيادة التعقيد وتصعيب كسر الشفرة.",
    },
    {
        id: 15,
        type: "tf",
        q: "PGP cannot achieve confidentiality or Authentication.",
        ans: false,
        why: "العبارة الصحيحة: PGP can achieve both confidentiality and Authentication.\nالمحاضرة 7: بروتوكول PGP قادر على تحقيق كل من السرية والمصادقة معاً عن طريق دمج التشفير بالمفاتيح المتماثلة وغير المتماثلة مع التوقيع الرقمي.",
    },
    {
        id: 16,
        type: "tf",
        q: "PGP segments message if too big.",
        ans: true,
        why: "المحاضرة 7: من خصائص بروتوكول PGP أنه يقوم بتقسيم (Segmentation) الرسائل الكبيرة إلى أجزاء لتتناسب مع قيود الإرسال في شبكات البريد الإلكتروني.",
    },
    {
        id: 17,
        type: "tf",
        q: "In digital signature, sender encrypt hash functions of message with sender private key.",
        ans: true,
        why: "المحاضرة 7: لإنشاء التوقيع الرقمي (Digital Signature)، يتم استخراج قيمة التجزئة (Hash) للرسالة ثم تشفيرها باستخدام المفتاح الخاص للمرسل لإثبات هويته.",
    },
    {
        id: 18,
        type: "tf",
        q: "A key distribution center (KDC) creates a secret key for each member.",
        ans: true,
        why: "المحاضرة 1 و 7: مركز توزيع المفاتيح (KDC) مسؤول عن توليد مفاتيح سرية وتوزيعها بشكل آمن على الأعضاء لتمكينهم من التواصل دون الحاجة لتبادل المفاتيح يدوياً.",
    },
    {
        id: 19,
        type: "tf",
        q: "S-DES is not considered secure for practical use due to its small key size. However, it serves as a valuable educational tool for understanding the fundamental",
        ans: true,
        why: "المحاضرة 3: خوارزمية S-DES (Simplified DES) صُممت كأداة تعليمية مبسطة لفهم هيكل خوارزميات التشفير الكتلي، وهي غير آمنة للاستخدام الفعلي لصغر مفتاحها.",
    },
    {
        id: 20,
        type: "tf",
        q: "AES is a asymmetric-key algorithm, meaning there are two key used for encryption and decryption.",
        ans: false,
        why: "العبارة الصحيحة: AES is a symmetric-key algorithm, meaning there is one key used for encryption and decryption.\nالمحاضرة 4: خوارزمية AES تعتبر خوارزمية تشفير متماثل (Symmetric-key) حيث تعتمد على مفتاح واحد فقط لتنفيذ عمليتي التشفير وفك التشفير.",
    },
    {
        id: 21,
        type: "tf",
        q: "Avalanche Effect means a small change in the input should result in a significantly different hash value.",
        ans: false,
        why: "العبارة الصحيحة: Avalanche Effect means a small change in the plaintext or key should result in a significantly different ciphertext.\nالمحاضرة 3 والمحاضرة 4: تأثير الانهيار (Avalanche Effect) قُدم كخاصية أساسية لخوارزميات التشفير الكتلي (مثل DES و AES)، حيث أن تغيير بت واحد في النص الأصلي أو المفتاح يُحدث تغييراً كبيراً وعشوائياً في كتل النص المشفر.",
        action: "تنبيه هام: السؤال التالي اجابته تختلف عن الاجابة في جروب السيريال, اجابة جروب السيريال هى [true]. و التحليل الظاهر هو تحليل لاجابة الموقع",
    },
    {
        id: 22,
        type: "tf",
        q: "In asymmetric encryption, sender and recipient shares two different public keys.",
        ans: false,
        why: "العبارة الصحيحة: In asymmetric encryption, each user has their own pair of keys (public and private), and the sender uses the recipient's public key to encrypt.\nالمحاضرة 5: في التشفير غير المتماثل، يمتلك كل شخص زوجاً خاصاً به من المفاتيح، ولا يتم إرسال رسالة بمشاركة مفاتيح عامة كأسرار، بل يتم التشفير بالمفتاح العام للطرف المستقبل وفك التشفير بمفتاحه الخاص.",
    },
];
