const QUESTIONS = [
    {
        id: 1,
        type: "tf",
        q: "In the electronic codebook (ECB) mode, plaintext is handled one block at a time and each block of plaintext is encrypted using different key.",
        ans: false,
        why: "المحاضرة 6: في نمط (ECB)، يتم تشفير كل كتلة من النص بشكل مستقل باستخدام نفس المفتاح (same key) وليس مفتاحاً مختلفاً لكل كتلة.",
    },
    {
        id: 2,
        type: "tf",
        q: "Most significant characteristic of ECB is that, if the same b -bit block of plaintext, it produces the same ciphertext.",
        ans: true,
        why: "المحاضرة 6: نظراً لأن نمط (ECB) يعالج كل كتلة بشكل مستقل باستخدام نفس المفتاح، فإن تكرار نفس كتلة النص الأصلي سينتج عنه دائماً نفس كتلة النص المشفر.",
    },
    {
        id: 3,
        type: "tf",
        q: "AES is a asymmetric-key algorithm, meaning there are two key used for encryption and decryption.",
        ans: false,
        why: "المحاضرة 4: خوارزمية (AES) هي خوارزمية تشفير متماثل (Symmetric)، مما يعني أنها تستخدم مفتاحاً واحداً فقط للتشفير وفك التشفير وليس مفتاحين.",
    },
    {
        id: 4,
        type: "tf",
        q: "Larger key size means greater security but may decrease encryption/decryption speeds.",
        ans: true,
        why: "المحاضرة 2: من القواعد العامة لتصميم التشفير المتماثل أن زيادة حجم المفتاح توفر أماناً أعلى وصعوبة في الكسر، لكنها في المقابل تزيد من عبء المعالجة مما قد يبطئ سرعة النظام.",
    },
    {
        id: 5,
        type: "tf",
        q: "If the algorithm can be concisely and clearly explained, it is easier to analyse that algorithm for cryptanalytic vulnerabilities.",
        ans: true,
        why: "المحاضرة 2: من معايير تصميم خوارزميات التشفير سهولة التحليل؛ فإذا أمكن شرح الخوارزمية بوضوح، سيصبح من الأسهل على المحللين كشف أي نقاط ضعف (Vulnerabilities) فيها.",
    },
    {
        id: 6,
        type: "tf",
        q: "In DES algorithm, it starts with permutation and ends with substitution.",
        ans: false,
        why: "المحاضرة 3: خوارزمية DES تبدأ بعملية تبديل أولي (Initial Permutation) وتنتهي أيضاً بعملية تبديل نهائي (Final Permutation)، وليس بعملية تعويض.",
    },
    {
        id: 7,
        type: "tf",
        q: "Public-key encryption is a general-purpose technique that has made symmetric encryption obsolete.",
        ans: false,
        why: "المحاضرة 2: التشفير المتماثل لا يزال التقنية الأساسية والأكثر استخداماً، والتشفير بالمفتاح العام يُستخدم بالتكامل معه ولم يجعله قديماً أو عفا عليه الزمن (Obsolete).",
    },
    {
        id: 8,
        type: "tf",
        q: "Hash function used to compare messages, If H(x) = H(y), Then x=y but you cannot know x or y.",
        ans: true,
        why: "المحاضرة 1: دالة التجزئة (Hash) تستخدم للتحقق من سلامة الرسائل؛ فإذا تطابقت قيمة التجزئة نستنتج تطابق الرسالة، لكن خاصية الاتجاه الواحد تمنعنا من عكس العملية لمعرفة الرسالة الأصلية.",
    },
    {
        id: 9,
        type: "tf",
        q: "There are five modes of operation that are intended for use with any symmetric block cipher, including triple DES and AES.",
        ans: true,
        why: "المحاضرة 6: حدد المعهد الوطني للمعايير والتكنولوجيا (NIST) خمسة أنماط تشغيل قياسية (Modes of Operation) لتُستخدم مع أي خوارزمية تشفير كتلي مثل DES و AES.",
    },
    {
        id: 10,
        type: "tf",
        q: "The size of cipher block data in DES is 128 byte while the size of block data in AES is 64 bit.",
        ans: false,
        why: "المحاضرة 3 و 4: الأرقام معكوسة؛ فحجم الكتلة في خوارزمية (DES) هو 64 بت (المحاضرة 3)، بينما حجم الكتلة في خوارزمية (AES) هو 128 بت (المحاضرة 4).",
    },
    {
        id: 11,
        type: "mcq",
        q: "Used to protect blocks of data, such as messages, from alteration",
        opts: ["Integrity.", "Authentication.", "Vulnerability."],
        ans: 0,
        why: "المحاضرة 1: خوارزميات نزاهة البيانات (Data integrity) هي التي تُستخدم خصيصاً لحماية كتل البيانات والتأكد من عدم تعرضها لأي تعديل أو تغيير (alteration).",
    },
    {
        id: 12,
        type: "mcq",
        q: "DES encryption starts with",
        opts: ["Permutation", "Substitution", "Confusion"],
        ans: 0,
        why: "المحاضرة 3: أول خطوة فعلية في تشفير كتلة البيانات في خوارزمية DES هي تمريرها عبر دالة التبديل الأولي (Initial Permutation).",
    },
    {
        id: 13,
        type: "mcq",
        q: "AES encryption starts with",
        opts: ["Permutation", "Substitution", "Confusion"],
        ans: 1,
        why: "المحاضرة 4: في داخل جولات خوارزمية AES، الخطوة الأولى والأساسية التي تُحدث التشويش في البيانات هي عملية التعويض باستخدام صناديق (SubBytes).",
    },
    {
        id: 14,
        type: "mcq",
        q: "Symmetric encryption suitable for",
        opts: ["Short message.", "Long message.", "Short and long message."],
        ans: 1,
        why: "المحاضرة 2: التشفير المتماثل يتميز بسرعته وكفاءته العالية، مما يجعله الأداة الأنسب لتشفير الرسائل أو الملفات والبيانات الطويلة (Long message).",
        action: "تنبيه هام: السؤال التالي اجابته تختلف عن الاجابة في جروب السيريال, اجابة جروب السيريال هى [short and long message]. و التحليل الظاهر هو تحليل لاجابة الموقع",
    },
    {
        id: 15,
        type: "mcq",
        q: "Ensuring timely and reliable access to and use of information.",
        opts: ["confidentiality", "integrity", "availability"],
        ans: 2,
        why: "المحاضرة 1: التوافر (Availability) هو أحد أضلاع مثلث الأمن (CIA) والذي يعني ضمان وصول المستخدمين المصرح لهم للمعلومات بشكل موثوق وفي الوقت المناسب.",
    },
    {
        id: 16,
        type: "mcq",
        q: "A ............. takes place when one entity pretends to be a different entity.",
        opts: ["Masquerade.", "Replay.", "Modification"],
        ans: 0,
        why: "المحاضرة 1: هجوم التنكر أو انتحال الشخصية (Masquerade) هو هجوم نشط يحدث عندما يحاول كيان التظاهر بأنه كيان آخر موثوق به.",
    },
    {
        id: 17,
        type: "mcq",
        q: "In OFB mode, we use ....... function in encryption and ........ function in decryption",
        opts: [
            "encryption – decryption.",
            "encryption – encryption.",
            "decryption - encryption",
        ],
        ans: 1,
        why: "المحاضرة 6: نمط Output Feedback (OFB) يعتمد على توليد تيار من المفاتيح ودمجه بـ XOR مع النص، لذلك هو لا يحتاج سوى لدالة التشفير (Encryption) في كلا الاتجاهين.",
    },
    {
        id: 18,
        type: "mcq",
        q: "The bit errors in transmission propagate in .....",
        opts: ["ECB", "CFB", "OFB"],
        ans: 1,
        why: "المحاضرة 6: في نمط Cipher Feedback (CFB)، النص المشفر للكتلة السابقة يدخل كمدخل لتشفير الكتلة التالية، لذلك فإن أي خطأ في الإرسال سينتشر (Propagate) للكتل التي تليه.",
    },
    {
        id: 19,
        type: "mcq",
        q: "Applying AES algorithm to similar data blocks leads to",
        opts: [
            "similar hash values.",
            "similar cipher blocks",
            "different cipher blocks",
        ],
        ans: 2,
        why: "المحاضرة 3 و 4: بفضل خاصية تأثير الانهيار (Avalanche Effect) الموجودة بقوة في خوارزميات التشفير الكتلي كـ AES، فإن أي تشابه بين الكتل سينتج عنه كتل مشفرة مختلفة تماماً.",
        action: "تنبيه هام: السؤال التالي اجابته تختلف عن الاجابة في جروب السيريال, اجابة جروب السيريال هى [similar cipher blocks]. و التحليل الظاهر هو تحليل لاجابة الموقع",
    },
    {
        id: 20,
        type: "mcq",
        q: "In the AES, The structure is quite simple. For both encryption and decryption, the cipher begins with an ....... stage, followed by ....... rounds that each includes all four stages, followed by a tenth round of three stages.",
        opts: [
            "AddRoundKey – ten.",
            "Initial permutation – nine.",
            "AddRoundKey – nine.",
        ],
        ans: 2,
        why: "المحاضرة 4: هيكل AES يبدأ بمرحلة (AddRoundKey)، ثم تليها 9 جولات (Nine) قياسية تحتوي على العمليات الأربع، ثم جولة عاشرة وأخيرة تفتقر لإحدى العمليات.",
    },
    {
        id: 21,
        type: "mcq",
        q: "DES uses ........ S-boxes, each with a ......-bit input and a .......-bit output.",
        opts: ["8 - 8 - 8", "8 - 6 - 6", "8 - 6 - 4"],
        ans: 2,
        why: "المحاضرة 3: تستخدم خوارزمية DES ثمانية صناديق تعويض (8 S-boxes) لتقليص حجم البيانات، حيث يأخذ الصندوق 6 بت كمدخل ويخرج 4 بت.",
    },
    {
        id: 22,
        type: "mcq",
        q: "In DES algorithm, the block cipher size is .........bit, it divided into two halves, LPT and RPT . each half expanded to ..........bit.",
        opts: ["64 - 32.", "128 - 48.", "64 - 48"],
        ans: 2,
        why: "المحاضرة 3: حجم الكتلة الكلي في DES هو 64 بت. يتم قسمتها لنصفين كل منهما 32 بت، وداخل الجولة يتم توسيع النصف الأيمن من 32 بت إلى 48 بت ليتم دمجه مع المفتاح الفرعي.",
    },
    {
        id: 23,
        type: "mcq",
        q: "A public-key encryption scheme has ....... ingredients",
        opts: ["8", "6", "4"],
        ans: 1,
        why: "المحاضرة 5: يحتوي أي نظام تشفير بالمفتاح العام (Public-key) على 6 عناصر أساسية هي: النص الأصلي، خوارزمية التشفير، المفتاح العام، المفتاح الخاص، النص المشفر، وخوارزمية فك التشفير.",
    },
    {
        id: 24,
        type: "mcq",
        q: "Attempts to learn or make use of information from the system but does not affect system resources",
        opts: ["Active attack.", "passive attack.", "periodic attack"],
        ans: 1,
        why: "المحاضرة 1: الهجوم السلبي (Passive attack) هو الهجوم الذي يهدف فقط للتنصت على المعلومات أو التقاطها دون أي إحداث تعديل أو تدمير لموارد النظام.",
    },
    {
        id: 25,
        type: "mcq",
        q: "......... Prevents either sender or receiver from denying a transmitted message",
        opts: ["Nonrepudiation", "Integrity", "Availability"],
        ans: 0,
        why: "المحاضرة 1: خدمة عدم الإنكار (Nonrepudiation) تضمن أنه عند إرسال رسالة، يمكن إثبات هوية المرسل الحقيقي بشكل لا يمكنه إنكاره لاحقاً، وكذلك الأمر بالنسبة للمستقبل.",
    },
    {
        id: 26,
        type: "mcq",
        q: "When Attacker tries every possible key on a piece of ciphertext until an intelligible translation into plaintext is obtained, it is called",
        opts: ["Brute-force attack.", "Cryptanalysis.", "Trying."],
        ans: 0,
        why: "المحاضرة 2: هجوم القوة الغاشمة (Brute-force attack) يعتمد على التجربة المنهجية لكل الاحتمالات المتاحة للمفتاح السري لحين الوصول إلى النص المفهوم.",
    },
    {
        id: 27,
        type: "mcq",
        q: "In ......... each block of plaintext bits is encoded independently using the same key",
        opts: ["CBC", "ECB", "CFB"],
        ans: 1,
        why: "المحاضرة 6: النمط الإلكتروني (ECB) هو النمط الوحيد الذي تُعالج فيه وتُشفّر كل كتلة بيانات بشكل منفصل ومستقل تماماً عن باقي الكتل، باستخدام المفتاح ذاته.",
    },
    {
        id: 28,
        type: "mcq",
        q: "In CFB mode, we use ....... function in encryption and ......... function in decryption",
        opts: [
            "encryption – decryption.",
            "encryption – encryption.",
            "decryption – encryption",
        ],
        ans: 1,
        why: "المحاضرة 6: نمط Cipher Feedback (CFB) يحول خوارزمية التشفير الكتلي إلى تيار تشفير؛ لذا نستخدم خوارزمية التشفير (Encryption) لتوليد التدفق في حالتي التشفير وفك التشفير.",
    },
    {
        id: 29,
        type: "mcq",
        q: "The bit errors in transmission do not propagate in ..........",
        opts: ["ECB and CFB", "CFB and OFB", "OFB and CRT"],
        ans: 2,
        why: "المحاضرة 6: في نمطي (OFB) و العداد (CRT)، توليد تيار المفتاح مستقل كلياً عن الرسالة، بالتالي إذا حدث خطأ في بت واحد أثناء النقل فلن ينتشر للكتل الأخرى.",
    },
    {
        id: 30,
        type: "mcq",
        q: "Applying hash function to different messages size leads to",
        opts: [
            "similar hash values.",
            "similar size of hash.",
            "different message size.",
        ],
        ans: 1,
        why: "المحاضرة 1: وظيفة دوال التجزئة الكريبتوغرافية الأساسية هي ضغط أي رسالة مهما اختلف طولها أو حجمها لتوليد مخرج نهائي ذو حجم أو طول ثابت ومماثل دائماً (Similar size of hash).",
    },
    {
        id: 31,
        type: "essay",
        q: "Explain briefly how can 128-bit key generate different round keys in AES algorithm.",
        ans: "<p>The 128-bit original key is expanded into an array of 44 words (each word is 32 bits) using a process called <b>Key Expansion</b>.</p><ul><li>This expansion provides 11 separate round keys (each being 4 words or 128 bits): one for the initial 'AddRoundKey' stage and 10 for the rounds.</li><li>The algorithm generates these keys sequentially using an auxiliary function that includes operations like <b>RotWord</b> (circular byte shift), <b>SubWord</b> (using the S-box for non-linear substitution), and XORing with a round constant (<b>Rcon</b>) to eliminate symmetry.</li><li>This ensures every round gets a distinct key.</li></ul>",
        why: "المحاضرة 4 والمحاضرة 5: تم شرح تفاصيل خوارزمية (AES Key Expansion) وكيفية توليد مصفوفة مفاتيح من 44 كلمة من المفتاح الأصلي باستخدام دوال مساعدة (RotWord, SubWord) وثوابت جولة (Rcon) لإزالة التماثل.",
    },
    {
        id: 32,
        type: "essay",
        q: "Compare between end to end encryption and link encryption.",
        ans: "<table border='1' style='width:100%; border-collapse:collapse; text-align:left;' cellpadding='8'><tr><th style='background-color:#f2f2f2;'>Feature</th><th style='background-color:#f2f2f2;'>Link Encryption</th><th style='background-color:#f2f2f2;'>End-to-End Encryption</th></tr><tr><td><b>Scope</b></td><td>Encrypts all transmitted data, including headers and routing info.</td><td>Encryption occurs only between the original source and the final destination.</td></tr><tr><td><b>Intermediate Nodes</b></td><td>Data is decrypted then re-encrypted at every intermediate node (like a router).</td><td>Intermediate nodes route the packet without decrypting the payload (headers usually remain unencrypted).</td></tr><tr><td><b>Keys Required</b></td><td>Requires paired keys for all connected links.</td><td>Requires the two end devices to share a key.</td></tr></table>",
        why: "المحاضرة 7: مقارنة صريحة بين (Link encryption) الذي يشفر كل شيء ويتم فك تشفيره في كل محطة، وبين (End-to-End encryption) الذي يتم بين المصدر والوجهة فقط ويحتاج لمفاتيح مشتركة بينهما.",
    },
    {
        id: 33,
        type: "essay",
        q: "What is PGP? Explain the use of Hash code function in PGP.",
        ans: "<p><b>PGP (Pretty Good Privacy)</b> is a widely used cryptographic protocol providing confidentiality and authentication for data communication, mostly used in secure email.</p><p><b>Use of Hash code function in PGP:</b></p><ul><li>To achieve Authentication (Digital Signature), PGP calculates a Hash code of the sender's original message.</li><li>This hash code is then encrypted using the sender's Private Key.</li><li>The receiver can decrypt it using the sender's Public Key and compare the hash to verify the sender's identity and ensure the message wasn't altered.</li></ul>",
        why: "المحاضرة 7: بروتوكول (PGP) يستخدم لحماية البريد الإلكتروني. دالة التجزئة (Hash code) تُستخدم فيه لتحقيق المصادقة (Authentication) بإنشاء توقيع رقمي يتم تشفيره بالمفتاح الخاص للمرسل.",
    },
    {
        id: 34,
        type: "essay",
        q: "Explain briefly how can 56-bit key used to encrypt block data of 64-bit in DES algorithm.",
        ans: "<p>In DES, the encryption process involves both data and key transformations:</p><ol><li>The 64-bit plaintext block goes through an Initial Permutation (IP) and is split into a 32-bit Left Plain Text (LPT) and a 32-bit Right Plain Text (RPT).</li><li>During each of the 16 rounds, the 32-bit RPT is expanded into 48 bits using an Expansion Permutation.</li><li>Meanwhile, the 56-bit key undergoes a <b>Key Transformation</b> (shifts and compression) to produce a 48-bit subkey for that specific round.</li><li>The 48-bit expanded RPT is then XORed with the 48-bit round subkey.</li><li>The result is passed through 8 S-boxes to shrink it back to 32 bits, which is then permuted and XORed with the LPT.</li></ol>",
        why: "المحاضرة 3: تفصيل خطوات الجولة في (DES) حيث يتم توسيع نصف البيانات الأيمن من 32 إلى 48 بت، في حين يتم ضغط المفتاح من 56 إلى مفتاح فرعي 48 بت لكل جولة ليتم دمجهما بعملية XOR.",
    },
    {
        id: 35,
        type: "essay",
        q: "Compare between DES and AES from block size, key size, number of rounds, what does it start with and end, what dose the abbreviation stand for?",
        ans: "<table border='1' style='width:100%; border-collapse:collapse; text-align:left;' cellpadding='8'><tr><th style='background-color:#f2f2f2;'>Feature</th><th style='background-color:#f2f2f2;'>DES</th><th style='background-color:#f2f2f2;'>AES</th></tr><tr><td><b>Abbreviation</b></td><td>Data Encryption Standard</td><td>Advanced Encryption Standard</td></tr><tr><td><b>Block Size</b></td><td>64-bit</td><td>128-bit</td></tr><tr><td><b>Key Size</b></td><td>56-bit</td><td>128, 192, or 256-bit</td></tr><tr><td><b>Number of Rounds</b></td><td>16 rounds</td><td>10, 12, or 14 rounds</td></tr><tr><td><b>Starts with</b></td><td>Initial Permutation (IP)</td><td>AddRoundKey</td></tr><tr><td><b>Ends with</b></td><td>Final Permutation (FP)</td><td>A final round lacking the MixColumns stage</td></tr></table>",
        why: "المحاضرة 3 والمحاضرة 4: مقارنة شاملة لمعايير الخوارزميتين (DES) و (AES) من حيث الخصائص المعمارية (حجم الكتلة، والمفتاح، والجولات، والبداية والنهاية).",
    },
    {
        id: 36,
        type: "essay",
        q: "Using PlayFair cipher, encrypt FREEDOM. Where the key is PALESTINE.",
        ans: "<p><b>1. Build 5x5 Matrix with key PALESTINE (ignoring duplicates) and rest of alphabet (I/J combined):</b></p><pre style='background:#f4f4f4; padding:10px; border-radius:5px;'>P A L E S<br>T I N B C<br>D F G H K<br>M O Q R U<br>V W X Y Z</pre><p><b>2. Prepare text (FREEDOM):</b> Split into pairs. Insert 'X' between identical letters (EE).<br>Pairs: FR, EX, ED, OM.</p><p><b>3. Encrypt pairs:</b></p><ul><li><b>FR</b> forms rectangle with corners F(2,1) and R(3,3) &rarr; Replace with H and O &rarr; <b>HO</b></li><li><b>EX</b> forms rectangle with E(0,3) and X(4,2) &rarr; Replace with L and Y &rarr; <b>LY</b></li><li><b>ED</b> forms rectangle with E(0,3) and D(2,0) &rarr; Replace with P and H &rarr; <b>PH</b></li><li><b>OM</b> are in the same row (3,1) and (3,0). Shift right: O becomes Q, M becomes O &rarr; <b>QO</b>.</li></ul><p><b>Ciphertext:</b> HO LY PH QO</p>",
        why: "المحاضرة 2: تطبيق عملي لخوارزمية (Playfair cipher) ببناء المصفوفة وتقسيم الكلمة لأزواج مع كسر التكرار بحرف X، ثم تطبيق قواعد الاستبدال (المستطيل والصف الموحد).",
    },
    {
        id: 37,
        type: "essay",
        q: "What are the modes of operation? explain with drawing one of them that disappear repeated blocks.",
        ans: "<p><b>Modes of operation</b> are techniques defined by NIST to adapt symmetric block ciphers (like AES/DES) for various applications securely (e.g., ECB, CBC, CFB, OFB, CTR).</p><p><b>The mode that hides (disappears) repeated blocks is Cipher Block Chaining (CBC):</b></p><ul><li><b>Explanation:</b> In CBC, the encryption input is NOT the raw plaintext. Instead, the plaintext block is first XORed with the preceding ciphertext block [ <code>C<sub>j</sub> = E(K, P<sub>j</sub> XOR C<sub>j-1</sub>)</code> ].</li><li>For the first block, an Initialization Vector (IV) is used.</li><li>Because the ciphertext of block 1 affects block 2, repeating plaintext blocks will produce entirely different ciphertext blocks, effectively hiding patterns.</li></ul>",
        why: "المحاضرة 6: تعريف أنماط التشغيل. نمط السلسلة (CBC) يتغلب على مشكلة (ECB) في كشف الكتل المكررة عن طريق دمج كل كتلة بنتيجة التشفير للكتلة السابقة بـ XOR.",
    },
    {
        id: 38,
        type: "essay",
        q: "What are the uses of Hash Code Function? Explain, how it can help in discovering virus on your PC?",
        ans: "<p><b>Uses of Hash Code Function:</b></p><ul><li>Data Integrity</li><li>Authentication</li><li>Digital Signatures</li><li>Comparing messages securely</li></ul><p><b>How it helps in discovering viruses:</b></p><ul><li>A Hash function takes a file's contents and produces a unique fixed-size code.</li><li>Since <code>H(x) = H(y)</code> only if <code>x = y</code>, any slight change in the file changes its hash value completely.</li><li>Security systems can calculate and store the hashes of clean files. If a virus infects a PC and alters a file, recalculating the file's hash will result in a completely different value compared to the stored clean hash, thus alerting the system to the virus.</li></ul>",
        why: "المحاضرة 1: دوال التجزئة تستخدم لحماية النزاهة والمقارنة. عند إصابة ملف بفيروس، يتغير محتوى الملف وبالتالي تتغير قيمة الـ Hash الخاصة به، مما يكشف التلاعب.",
    },
    {
        id: 39,
        type: "essay",
        q: "Explain with drawing the KDC role in Symmetric encryption?",
        ans: "<p>The <b>Key Distribution Center (KDC)</b> solves the complex key management problem in symmetric encryption. Instead of all users sharing keys with everyone, each user shares a single Master Secret Key only with the KDC.</p><p><b>Role of KDC:</b></p><ol><li>When User A wants to talk to User B, A requests a session key from the KDC.</li><li>The KDC generates a temporary, random 'Session Key' for them.</li><li>It encrypts one copy of this session key with User A's master key, and another copy with User B's master key, and sends them to the users.</li><li>A and B decrypt these to get the shared session key and communicate securely for that session.</li></ol>",
        why: "المحاضرة 1 والمحاضرة 7: شرح دور مركز توزيع المفاتيح (KDC) الذي يمتلك مفتاحاً سرياً مع كل مستخدم، ويقوم بتوليد وتوزيع مفاتيح جلسة (Session keys) مؤقتة بآمان لتمكين التواصل.",
    },
    {
        id: 40,
        type: "essay",
        q: "Write the processes of generation keys in RSA. then Write the encryption function equation of encryption & decryption. If p=7 and q=19. Calculate the 'n' and &phi;(n) to select the public and private keys. Then encrypt the message M=12.",
        ans: "<p><b>Processes of generation keys in RSA:</b></p><ol><li>Choose 2 primes p, q.</li><li>Compute <code>n = p * q</code>.</li><li>Compute <code>&phi;(n) = (p - 1)(q - 1)</code>.</li><li>Select 'e' such that <code>gcd(e, &phi;(n)) = 1</code>.</li><li>Compute 'd' such that <code>e * d = 1 mod &phi;(n)</code>.</li></ol><p><b>Equations:</b><br>Encrypt: <code>C = M<sup>e</sup> mod n</code><br>Decrypt: <code>M = C<sup>d</sup> mod n</code></p><p><b>Calculation for p=7, q=19, M=12:</b></p><ul><li><code>n = 7 * 19 = 133</code></li><li><code>&phi;(n) = (7 - 1) * (19 - 1) = 6 * 18 = 108</code></li><li>Let's choose <code>e = 5</code> (since gcd(5, 108) = 1).</li><li>Calculate d: <code>5 * d = 1 mod 108</code> &rarr; <code>d = 65</code> (because 5 * 65 = 325 = 3 * 108 + 1).</li><li><b>Public Key:</b> (5, 133), <b>Private Key:</b> (65, 133).</li><li><b>Encrypt M=12:</b> <code>C = 12<sup>5</sup> mod 133</code><br><code>12<sup>2</sup> = 144 = 11 mod 133</code><br><code>12<sup>4</sup> = 11<sup>2</sup> = 121 mod 133</code><br><code>12<sup>5</sup> = 121 * 12 = 1452</code><br><code>1452 mod 133 = 122</code><br><b>So, C = 122</b></li></ul>",
        why: "المحاضرة 5: خطوات خوارزمية (RSA) للتشفير غير المتماثل بالكامل مع الحسابات الرياضية لتوليد القيم المطلوبة وتطبيق التشفير المعتمد على Modulo.",
    },
    {
        id: 41,
        type: "essay",
        q: "Using Vigneer CIPHER, Encrypt the following plain text ' TEAMWORK IS VICTORY WAY ' Where the key is ( COOPERATION )",
        ans: "<p><b>Message:</b> T E A M W O R K I S V I C T O R Y W A Y<br><b>Key repeated:</b> C O O P E R A T I O N C O O P E R A T I</p><p><b>Method:</b> Add letter numerical values (A=0..Z=25) modulo 26.</p><div style='column-count:2; column-gap: 20px;'><ul><li>T(19)+C(2)=21 (V)</li><li>E(4)+O(14)=18 (S)</li><li>A(0)+O(14)=14 (O)</li><li>M(12)+P(15)=27=1 (B)</li><li>W(22)+E(4)=26=0 (A)</li><li>O(14)+R(17)=31=5 (F)</li><li>R(17)+A(0)=17 (R)</li><li>K(10)+T(19)=29=3 (D)</li><li>I(8)+I(8)=16 (Q)</li><li>S(18)+O(14)=32=6 (G)</li><li>V(21)+N(13)=34=8 (I)</li><li>I(8)+C(2)=10 (K)</li><li>C(2)+O(14)=16 (Q)</li><li>T(19)+O(14)=33=7 (H)</li><li>O(14)+P(15)=29=3 (D)</li><li>R(17)+E(4)=21 (V)</li><li>Y(24)+R(17)=41=15 (P)</li><li>W(22)+A(0)=22 (W)</li><li>A(0)+T(19)=19 (T)</li><li>Y(24)+I(8)=32=6 (G)</li></ul></div><p><b>Ciphertext:</b> VSOBAFRDQGIKQHDVPWTG</p>",
        why: "المحاضرة 2: استخدام شفرة (Vigenere) متعددة الأبجديات بتكرار المفتاح ليتطابق مع طول النص، ثم جمع القيم العددية لكل حرف واستخراج الحرف المشفر.",
    },
];
