const QUESTIONS = [
    {
        id: 1,
        type: "tf",
        q: "In the electronic codebook (ECB) mode, plaintext is handled one block at a time and each block of plaintext is encrypted using different key.",
        ans: false,
        why: "المحاضرة 6: في نمط (ECB)، يتم تشفير كل كتلة من النص بشكل مستقل باستخدام نفس المفتاح (same key) وليس مفتاحاً مختلفاً لكل كتلة.",
    },
    {
        id: 2,
        type: "tf",
        q: "Most significant characteristic of ECB is that, if the same b -bit block of plaintext, it produces the same ciphertext.",
        ans: true,
        why: "المحاضرة 6: نظراً لأن نمط (ECB) يعالج كل كتلة بشكل مستقل باستخدام نفس المفتاح، فإن تكرار نفس كتلة النص الأصلي سينتج عنه دائماً نفس كتلة النص المشفر.",
    },
    {
        id: 3,
        type: "tf",
        q: "AES is a asymmetric-key algorithm, meaning there are two key used for encryption and decryption.",
        ans: false,
        why: "المحاضرة 4: خوارزمية (AES) هي خوارزمية تشفير متماثل (Symmetric)، مما يعني أنها تستخدم مفتاحاً واحداً فقط للتشفير وفك التشفير وليس مفتاحين.",
    },
    {
        id: 4,
        type: "tf",
        q: "Larger key size means greater security but may decrease encryption/decryption speeds.",
        ans: true,
        why: "المحاضرة 2: من القواعد العامة لتصميم التشفير المتماثل أن زيادة حجم المفتاح توفر أماناً أعلى وصعوبة في الكسر، لكنها في المقابل تزيد من عبء المعالجة مما قد يبطئ سرعة النظام.",
    },
    {
        id: 5,
        type: "tf",
        q: "If the algorithm can be concisely and clearly explained, it is easier to analyse that algorithm for cryptanalytic vulnerabilities.",
        ans: true,
        why: "المحاضرة 2: من معايير تصميم خوارزميات التشفير سهولة التحليل؛ فإذا أمكن شرح الخوارزمية بوضوح، سيصبح من الأسهل على المحللين كشف أي نقاط ضعف (Vulnerabilities) فيها.",
    },
    {
        id: 6,
        type: "tf",
        q: "In DES algorithm, it starts with permutation and ends with substitution.",
        ans: false,
        why: "المحاضرة 3: خوارزمية DES تبدأ بعملية تبديل أولي (Initial Permutation) وتنتهي أيضاً بعملية تبديل نهائي (Final Permutation)، وليس بعملية تعويض.",
    },
    {
        id: 7,
        type: "tf",
        q: "Public-key encryption is a general-purpose technique that has made symmetric encryption obsolete.",
        ans: false,
        why: "المحاضرة 2: التشفير المتماثل لا يزال التقنية الأساسية والأكثر استخداماً، والتشفير بالمفتاح العام يُستخدم بالتكامل معه ولم يجعله قديماً أو عفا عليه الزمن (Obsolete).",
    },
    {
        id: 8,
        type: "tf",
        q: "Hash function used to compare messages, If H(x) = H(y), Then x=y but you cannot know x or y.",
        ans: true,
        why: "المحاضرة 1: دالة التجزئة (Hash) تستخدم للتحقق من سلامة الرسائل؛ فإذا تطابقت قيمة التجزئة نستنتج تطابق الرسالة، لكن خاصية الاتجاه الواحد تمنعنا من عكس العملية لمعرفة الرسالة الأصلية.",
    },
    {
        id: 9,
        type: "tf",
        q: "There are five modes of operation that are intended for use with any symmetric block cipher, including triple DES and AES.",
        ans: true,
        why: "المحاضرة 6: حدد المعهد الوطني للمعايير والتكنولوجيا (NIST) خمسة أنماط تشغيل قياسية (Modes of Operation) لتُستخدم مع أي خوارزمية تشفير كتلي مثل DES و AES.",
    },
    {
        id: 10,
        type: "tf",
        q: "The size of cipher block data in DES is 128 byte while the size of block data in AES is 64 bit.",
        ans: false,
        why: "المحاضرة 3 و 4: الأرقام معكوسة؛ فحجم الكتلة في خوارزمية (DES) هو 64 بت (المحاضرة 3)، بينما حجم الكتلة في خوارزمية (AES) هو 128 بت (المحاضرة 4).",
    },
    {
        id: 11,
        type: "mcq",
        q: "Used to protect blocks of data, such as messages, from alteration",
        opts: ["Integrity.", "Authentication.", "Vulnerability."],
        ans: 0,
        why: "المحاضرة 1: خوارزميات نزاهة البيانات (Data integrity) هي التي تُستخدم خصيصاً لحماية كتل البيانات والتأكد من عدم تعرضها لأي تعديل أو تغيير (alteration).",
    },
    {
        id: 12,
        type: "mcq",
        q: "DES encryption starts with",
        opts: ["Permutation", "Substitution", "Confusion"],
        ans: 0,
        why: "المحاضرة 3: أول خطوة فعلية في تشفير كتلة البيانات في خوارزمية DES هي تمريرها عبر دالة التبديل الأولي (Initial Permutation).",
    },
    {
        id: 13,
        type: "mcq",
        q: "AES encryption starts with",
        opts: ["Permutation", "Substitution", "Confusion"],
        ans: 1,
        why: "المحاضرة 4: في داخل جولات خوارزمية AES، الخطوة الأولى والأساسية التي تُحدث التشويش في البيانات هي عملية التعويض باستخدام صناديق (SubBytes).",
    },
    {
        id: 14,
        type: "mcq",
        q: "Symmetric encryption suitable for",
        opts: ["Short message.", "Long message.", "Short and long message."],
        ans: 1,
        why: "المحاضرة 2: التشفير المتماثل يتميز بسرعته وكفاءته العالية، مما يجعله الأداة الأنسب لتشفير الرسائل أو الملفات والبيانات الطويلة (Long message).",
    },
    {
        id: 15,
        type: "mcq",
        q: "Ensuring timely and reliable access to and use of information.",
        opts: ["confidentiality", "integrity", "availability"],
        ans: 2,
        why: "المحاضرة 1: التوافر (Availability) هو أحد أضلاع مثلث الأمن (CIA) والذي يعني ضمان وصول المستخدمين المصرح لهم للمعلومات بشكل موثوق وفي الوقت المناسب.",
    },
    {
        id: 16,
        type: "mcq",
        q: "A ............. takes place when one entity pretends to be a different entity.",
        opts: ["Masquerade.", "Replay.", "Modification"],
        ans: 0,
        why: "المحاضرة 1: هجوم التنكر أو انتحال الشخصية (Masquerade) هو هجوم نشط يحدث عندما يحاول كيان التظاهر بأنه كيان آخر موثوق به.",
    },
    {
        id: 17,
        type: "mcq",
        q: "In OFB mode, we use ....... function in encryption and ........ function in decryption",
        opts: [
            "encryption – decryption.",
            "encryption – encryption.",
            "decryption - encryption",
        ],
        ans: 1,
        why: "المحاضرة 6: نمط Output Feedback (OFB) يعتمد على توليد تيار من المفاتيح ودمجه بـ XOR مع النص، لذلك هو لا يحتاج سوى لدالة التشفير (Encryption) في كلا الاتجاهين.",
    },
    {
        id: 18,
        type: "mcq",
        q: "The bit errors in transmission propagate in .....",
        opts: ["ECB", "CFB", "OFB"],
        ans: 1,
        why: "المحاضرة 6: في نمط Cipher Feedback (CFB)، النص المشفر للكتلة السابقة يدخل كمدخل لتشفير الكتلة التالية، لذلك فإن أي خطأ في الإرسال سينتشر (Propagate) للكتل التي تليه.",
    },
    {
        id: 19,
        type: "mcq",
        q: "Applying AES algorithm to similar data blocks leads to",
        opts: [
            "similar hash values.",
            "similar cipher blocks",
            "different cipher blocks",
        ],
        ans: 2,
        why: "المحاضرة 3 و 4: بفضل خاصية تأثير الانهيار (Avalanche Effect) الموجودة بقوة في خوارزميات التشفير الكتلي كـ AES، فإن أي تشابه بين الكتل سينتج عنه كتل مشفرة مختلفة تماماً.",
    },
    {
        id: 20,
        type: "mcq",
        q: "In the AES, The structure is quite simple. For both encryption and decryption, the cipher begins with an ....... stage, followed by ....... rounds that each includes all four stages, followed by a tenth round of three stages.",
        opts: [
            "AddRoundKey – ten.",
            "Initial permutation – nine.",
            "AddRoundKey – nine.",
        ],
        ans: 2,
        why: "المحاضرة 4: هيكل AES يبدأ بمرحلة (AddRoundKey)، ثم تليها 9 جولات (Nine) قياسية تحتوي على العمليات الأربع، ثم جولة عاشرة وأخيرة تفتقر لإحدى العمليات.",
    },
    {
        id: 21,
        type: "mcq",
        q: "DES uses ........ S-boxes, each with a ......-bit input and a .......-bit output.",
        opts: ["8 - 8 - 8", "8 - 6 - 6", "8 - 6 - 4"],
        ans: 2,
        why: "المحاضرة 3: تستخدم خوارزمية DES ثمانية صناديق تعويض (8 S-boxes) لتقليص حجم البيانات، حيث يأخذ الصندوق 6 بت كمدخل ويخرج 4 بت.",
    },
    {
        id: 22,
        type: "mcq",
        q: "In DES algorithm, the block cipher size is .........bit, it divided into two halves, LPT and RPT . each half expanded to ..........bit.",
        opts: ["64 - 32.", "128 - 48.", "64 - 48"],
        ans: 2,
        why: "المحاضرة 3: حجم الكتلة الكلي في DES هو 64 بت. يتم قسمتها لنصفين كل منهما 32 بت، وداخل الجولة يتم توسيع النصف الأيمن من 32 بت إلى 48 بت ليتم دمجه مع المفتاح الفرعي.",
    },
    {
        id: 23,
        type: "mcq",
        q: "A public-key encryption scheme has ....... ingredients",
        opts: ["8", "6", "4"],
        ans: 1,
        why: "المحاضرة 5: يحتوي أي نظام تشفير بالمفتاح العام (Public-key) على 6 عناصر أساسية هي: النص الأصلي، خوارزمية التشفير، المفتاح العام، المفتاح الخاص، النص المشفر، وخوارزمية فك التشفير.",
    },
    {
        id: 24,
        type: "mcq",
        q: "Attempts to learn or make use of information from the system but does not affect system resources",
        opts: ["Active attack.", "passive attack.", "periodic attack"],
        ans: 1,
        why: "المحاضرة 1: الهجوم السلبي (Passive attack) هو الهجوم الذي يهدف فقط للتنصت على المعلومات أو التقاطها دون أي إحداث تعديل أو تدمير لموارد النظام.",
    },
    {
        id: 25,
        type: "mcq",
        q: "......... Prevents either sender or receiver from denying a transmitted message",
        opts: ["Nonrepudiation", "Integrity", "Availability"],
        ans: 0,
        why: "المحاضرة 1: خدمة عدم الإنكار (Nonrepudiation) تضمن أنه عند إرسال رسالة، يمكن إثبات هوية المرسل الحقيقي بشكل لا يمكنه إنكاره لاحقاً، وكذلك الأمر بالنسبة للمستقبل.",
    },
    {
        id: 26,
        type: "mcq",
        q: "When Attacker tries every possible key on a piece of ciphertext until an intelligible translation into plaintext is obtained, it is called",
        opts: ["Brute-force attack.", "Cryptanalysis.", "Trying."],
        ans: 0,
        why: "المحاضرة 2: هجوم القوة الغاشمة (Brute-force attack) يعتمد على التجربة المنهجية لكل الاحتمالات المتاحة للمفتاح السري لحين الوصول إلى النص المفهوم.",
    },
    {
        id: 27,
        type: "mcq",
        q: "In ......... each block of plaintext bits is encoded independently using the same key",
        opts: ["CBC", "ECB", "CFB"],
        ans: 1,
        why: "المحاضرة 6: النمط الإلكتروني (ECB) هو النمط الوحيد الذي تُعالج فيه وتُشفّر كل كتلة بيانات بشكل منفصل ومستقل تماماً عن باقي الكتل، باستخدام المفتاح ذاته.",
    },
    {
        id: 28,
        type: "mcq",
        q: "In CFB mode, we use ....... function in encryption and ......... function in decryption",
        opts: [
            "encryption – decryption.",
            "encryption – encryption.",
            "decryption – encryption",
        ],
        ans: 1,
        why: "المحاضرة 6: نمط Cipher Feedback (CFB) يحول خوارزمية التشفير الكتلي إلى تيار تشفير؛ لذا نستخدم خوارزمية التشفير (Encryption) لتوليد التدفق في حالتي التشفير وفك التشفير.",
    },
    {
        id: 29,
        type: "mcq",
        q: "The bit errors in transmission do not propagate in ..........",
        opts: ["ECB and CFB", "CFB and OFB", "OFB and CRT"],
        ans: 2,
        why: "المحاضرة 6: في نمطي (OFB) و العداد (CRT)، توليد تيار المفتاح مستقل كلياً عن الرسالة، بالتالي إذا حدث خطأ في بت واحد أثناء النقل فلن ينتشر للكتل الأخرى.",
    },
    {
        id: 30,
        type: "mcq",
        q: "Applying hash function to different messages size leads to",
        opts: [
            "similar hash values.",
            "similar size of hash.",
            "different message size.",
        ],
        ans: 1,
        why: "المحاضرة 1: وظيفة دوال التجزئة الكريبتوغرافية الأساسية هي ضغط أي رسالة مهما اختلف طولها أو حجمها لتوليد مخرج نهائي ذو حجم أو طول ثابت ومماثل دائماً (Similar size of hash).",
    },
];
