const QUESTIONS = [
    {
        id: 1,
        type: "tf",
        q: "Link Encryption Encrypts all data that is transmitted, including the headers and routing information.",
        ans: true,
        why: "المحاضرة 7: في تشفير الوصلة (Link Encryption)، يتم تشفير جميع البيانات المرسلة بما في ذلك الترويسة (Headers) ومعلومات التوجيه لضمان سرية المسار بالكامل.",
    },
    {
        id: 2,
        type: "tf",
        q: "It is necessary to decide where to use the various security mechanisms.",
        ans: true,
        why: "المحاضرة 1 والمحاضرة 7: من أساسيات الأمن تحديد مواقع وآليات الحماية المناسبة (مثل الاختيار بين Link Encryption و End-to-End Encryption) بناءً على حاجة النظام.",
    },
    {
        id: 3,
        type: "tf",
        q: "security mechanism or algorithm should ignore potential attacks on the security features.",
        ans: false,
        why: "العبارة الصحيحة: Security mechanism or algorithm should CONSIDER potential attacks on the security features.\nالمحاضرة 1: آليات وخوارزميات الأمن صُممت خصيصاً لاكتشاف ومنع الهجمات المحتملة، ولا يجب أبداً تجاهلها (ignore) بل يجب أخذها في الاعتبار وتوقعها.",
    },
    {
        id: 4,
        type: "tf",
        q: "To create pseudorandom numbers we often use algorithmic technique which satisfy statistical randomness tests.",
        ans: true,
        why: "المحاضرة 7: لتوليد أرقام شبه عشوائية (Pseudorandom numbers)، نستخدم غالباً تقنيات خوارزمية تلبي اختبارات العشوائية الإحصائية رغم أنها قد تكون متوقعة إذا عُرفت الخوارزمية.",
    },
    {
        id: 5,
        type: "tf",
        q: "Symmetric-key cryptography is more efficient than asymmetric-key cryptography for enciphering large messages.",
        ans: true,
        why: "المحاضرة 7: التشفير المتماثل (Symmetric-key) أسرع بكثير وأكثر كفاءة من التشفير غير المتماثل، ولذلك يُستخدم دائماً لتشفير الرسائل أو البيانات كبيرة الحجم.",
    },
    {
        id: 6,
        type: "tf",
        q: "Symmetric-key cryptography needs a shared two secret keys between two parties.",
        ans: false,
        why: "العبارة الصحيحة: Symmetric-key cryptography needs a shared ONE secret key between two parties.\nالمحاضرة 5 والمحاضرة 7: التشفير المتماثل يتطلب مفتاحاً سرياً واحداً (One shared secret key) فقط يتم استخدامه في كلا العمليتين (التشفير وفك التشفير) بين الطرفين.",
    },
    {
        id: 7,
        type: "tf",
        q: "A KDC creates a secret key for each member. This secret key can be used only between the member and the KDC, not between two members.",
        ans: true,
        why: "المحاضرة 1: مركز توزيع المفاتيح (KDC) ينشئ مفتاحاً سرياً رئيسياً لكل عضو، ويُستخدم هذا المفتاح فقط للتواصل الآمن بين العضو والمركز (KDC) لغرض تبادل مفاتيح الجلسات لاحقاً.",
    },
    {
        id: 8,
        type: "tf",
        q: "A session symmetric key between two parties is used only once.",
        ans: true,
        why: "المحاضرة 1 والمحاضرة 7: مفتاح الجلسة (Session key) هو مفتاح متماثل مؤقت يُنشأ لغرض استخدامه في جلسة اتصال واحدة (Only once) لتعزيز الأمان، ثم يتم التخلص منه.",
    },
    {
        id: 9,
        type: "tf",
        q: "There are five modes of operation that are intended for use with any symmetric block cipher, including triple DES and AES.",
        ans: true,
        why: "المحاضرة 6: حددت منظمة (NIST) خمسة أنماط تشغيل (Modes of operation) قياسية يمكن استخدامها مع أي خوارزمية تشفير كتلي متماثل مثل (DES, Triple DES, AES).",
    },
    {
        id: 10,
        type: "tf",
        q: "any malicious program or code that is harmful to systems, is considered malware.",
        ans: true,
        why: "المحاضرة 1: أي برنامج أو كود ضار (Malicious program) يهدف إلى إلحاق الضرر بالأنظمة والموارد يُصنف تحت مصطلح البرمجيات الخبيثة (Malware).",
    },
    {
        id: 11,
        type: "mcq",
        q: "Attempts to learn or make use of information from the system but does not affect system resources",
        opts: ["Active attack.", "passive attack.", "periodic attack."],
        ans: 1,
        why: "المحاضرة 1: الهجوم السلبي (Passive attack) يهدف فقط للتنصت والاطلاع على المعلومات دون إحداث أي تغيير أو تأثير على موارد النظام.",
    },
    {
        id: 12,
        type: "mcq",
        q: "Ensuring timely and reliable access to and use of information.",
        opts: ["confidentiality", "integrity", "availability"],
        ans: 2,
        why: "المحاضرة 1: التوافر (Availability) هو التأكد من أن الأنظمة تعمل فوراً وبشكل موثوق، ولا يتم حجب الخدمة عن المستخدمين المصرح لهم.",
    },
    {
        id: 13,
        type: "mcq",
        q: "We can define ECB mode as",
        opts: ["Cj = E(K, Pj)", "Cj = E(Kj, Pj)", "Cj = E(Kj, P)"],
        ans: 0,
        why: "المحاضرة 6: في نمط (ECB)، يتم تشفير كل كتلة من النص (Pj) بشكل مستقل تماماً باستخدام نفس المفتاح الثابت (K) لإنتاج الكتلة المشفرة (Cj)، لذلك المعادلة هي Cj = E(K, Pj).",
    },
    {
        id: 14,
        type: "mcq",
        q: "........... Prevents either sender or receiver from denying a transmitted message",
        opts: ["Nonrepudiation", "Integrity", "Availability"],
        ans: 0,
        why: "المحاضرة 1: خدمة عدم الإنكار (Nonrepudiation) توفر الإثبات القاطع الذي يمنع أياً من الطرفين (المرسل أو المستقبل) من إنكار إرسال أو استقبال الرسالة.",
    },
    {
        id: 15,
        type: "mcq",
        q: "In PGP, to achieve authentication the hash code of sender message encrypted with",
        opts: [
            "sender private key.",
            "sender public key.",
            "receiver private key.",
        ],
        ans: 0,
        why: "المحاضرة 7: في بروتوكول (PGP)، يتم تحقيق المصادقة (Authentication) عن طريق تشفير كود التجزئة (Hash code) للرسالة باستخدام المفتاح الخاص للمرسل (Sender private key).",
    },
    {
        id: 16,
        type: "mcq",
        q: "When Attacker tries every possible key on a piece of ciphertext until an intelligible translation into plaintext is obtained, it is called",
        opts: ["Brute-force attack.", "Cryptanalysis.", "Security."],
        ans: 0,
        why: "المحاضرة 2 والمحاضرة 3: يُعرف الهجوم الذي يعتمد على تجربة كل الاحتمالات الممكنة للمفتاح حتى الوصول إلى النص المفهوم باسم هجوم القوة الغاشمة (Brute-force attack).",
    },
    {
        id: 17,
        type: "mcq",
        q: "In .......... each block of plaintext bits is encoded independently using the same key",
        opts: ["CBC", "ECB", "CFB"],
        ans: 1,
        why: "المحاضرة 6: النمط الذي يُشفر فيه كل كتلة بشكل منفصل ومستقل كلياً باستخدام المفتاح ذاته هو نمط (Electronic Codebook - ECB).",
    },
    {
        id: 18,
        type: "mcq",
        q: "in CFB mode, we use ....... function in encryption and ........ function in decryption",
        opts: [
            "encryption – decryption.",
            "encryption – encryption.",
            "decryption - encryption",
        ],
        ans: 1,
        why: "المحاضرة 6: نمط Cipher Feedback (CFB) يحول خوارزمية التشفير الكتلي إلى تيار تشفير؛ لذا نستخدم دالة التشفير (Encryption) في كلتا العمليتين (التشفير وفك التشفير) لتوليد التدفق.",
    },
    {
        id: 19,
        type: "mcq",
        q: "The bit errors in transmission do not propagate in .....",
        opts: ["ECB and CFB", "CFB and OFB", "OFB and CRT"],
        ans: 2,
        why: "المحاضرة 6: في نمطي (OFB) والعداد (CTR - المكتوب في الورقة كخطأ مطبعي CRT)، يكون تيار المفتاح مستقلاً عن النص المشفر، لذلك فإن أخطاء النقل في بت واحد لا تنتشر للكتل المجاورة.",
    },
    {
        id: 20,
        type: "mcq",
        q: "Applying hash function to different messages size leads to",
        opts: [
            "similar hash values.",
            "similar size of hash.",
            "large message size.",
        ],
        ans: 1,
        why: "المحاضرة 5: أهم خصائص دالة التجزئة (Hash) هي قدرتها على أخذ رسائل ذات أحجام مختلفة وضغطها لإنتاج مخرج له طول أو حجم ثابت ومماثل دائماً (Similar size of hash).",
    },
];
