const QUESTIONS = [
    {
        id: 1,
        type: "mcq",
        q: "Which of the following is one of the objectives of this chapter?",
        opts: [
            "To build and configure computer networks",
            "To learn how to write a compiler",
            "To design the internal circuits of a CPU",
            "To describe the services an OS provides to users, processes and other systems",
        ],
        ans: 3,
        why: "Chapter 2 covers OS services, ways of structuring an OS, and how OSes are installed, customized and booted.",
    },
    {
        id: 2,
        type: "mcq",
        q: "Which topic lies OUTSIDE the stated objectives of Chapter 2?",
        opts: [
            "The various ways of structuring an operating system",
            "The services an OS provides to users and processes",
            "How an operating system boots",
            "Detailed comparison of CPU scheduling algorithms",
        ],
        ans: 3,
        why: "The objectives cover services, structure, and installation/boot. Scheduling algorithms belong to a later chapter.",
    },
    {
        id: 3,
        type: "mcq",
        q: "Operating-system user interfaces vary between:",
        opts: [
            "Kernel, shell and registry",
            "LAN, WAN and MAN",
            "Command-Line (CLI), Graphical User Interface (GUI) and Batch",
            "API, ABI and ISA",
        ],
        ans: 2,
        why: "The slide names CLI, GUI and Batch as the forms of user interface.",
    },
    {
        id: 4,
        type: "mcq",
        q: "Processes can communicate through:",
        opts: [
            "Registers or the stack only",
            "CLI or GUI",
            "ROM or RAM",
            "Shared memory or message passing",
        ],
        ans: 3,
        why: "The slide names both methods; they work on the same computer or between computers over a network.",
    },
    {
        id: 5,
        type: "mcq",
        q: "According to the slide, errors that the OS must detect may occur in:",
        opts: [
            "The network only",
            "The CPU and memory hardware, I/O devices, and user programs",
            "Hardware only",
            "User programs only",
        ],
        ans: 1,
        why: "The OS must be constantly aware of errors anywhere and take the right action for each type.",
    },
    {
        id: 6,
        type: "mcq",
        q: "In message-passing communication, who moves the packets between processes?",
        opts: [
            "The compiler",
            "The processes, by writing directly into each other's memory",
            "The user, by hand",
            "The operating system",
        ],
        ans: 3,
        why: "With message passing, processes hand messages to the OS, which delivers them. In shared memory, processes read and write a common region directly.",
    },
    {
        id: 7,
        type: "mcq",
        q: "Keeping track of which users use how much and what kinds of resources is called:",
        opts: [
            "Error detection",
            "Protection",
            "Resource allocation",
            "Accounting",
        ],
        ans: 3,
        why: "Accounting records resource usage, e.g., for billing or usage statistics.",
    },
    {
        id: 8,
        type: "mcq",
        q: "When a command-line interpreter is implemented in several different flavors, each flavor is called a:",
        opts: ["Shell", "API", "Device driver", "Kernel"],
        ans: 0,
        why: "Examples of shells: Bourne shell, C shell, bash.",
    },
    {
        id: 9,
        type: "mcq",
        q: "Where was the graphical user interface invented?",
        opts: ["Microsoft", "Xerox PARC", "IBM", "Bell Labs"],
        ans: 1,
        why: "The slide states the GUI desktop metaphor was invented at Xerox PARC.",
    },
    {
        id: 10,
        type: "mcq",
        q: "System calls are:",
        opts: [
            "The programming interface to the services provided by the OS",
            "Hardware instructions for arithmetic operations",
            "A network protocol between computers",
            "User application programs such as games",
        ],
        ans: 0,
        why: "System calls are how a program asks the OS to do something on its behalf.",
    },
    {
        id: 11,
        type: "mcq",
        q: "Which are the three most common APIs mentioned on the slide?",
        opts: [
            "BIOS, ROM and EPROM",
            "C, C++ and Python",
            "Win32 API, POSIX API and Java API",
            "CLI, GUI and Batch",
        ],
        ans: 2,
        why: "Win32 for Windows, POSIX for UNIX/Linux/Mac OS X, and the Java API for the JVM.",
    },
    {
        id: 12,
        type: "mcq",
        q: "In the file-copy example, what is the first thing the program does?",
        opts: [
            "Terminate normally",
            "Acquire the input file name",
            "Write to the output file",
            "Close the output file",
        ],
        ans: 1,
        why: "The sequence starts by acquiring the input file name (prompt on screen, accept input).",
    },
    {
        id: 13,
        type: "mcq",
        q: "In the file-copy system-call sequence, what happens if the output file already exists?",
        opts: [
            "The existing file is renamed automatically",
            "The file is overwritten silently",
            "The data is appended to the existing file",
            "The program aborts",
        ],
        ans: 3,
        why: 'The slide shows "Create output file – if file exists, abort". (A real program might ask the user instead.)',
    },
    {
        id: 14,
        type: "mcq",
        q: "The ReadFile() function belongs to which API?",
        opts: ["Standard C library", "Java API", "Win32 API", "POSIX API"],
        ans: 2,
        why: "ReadFile() is a Win32 function for reading from a file.",
    },
    {
        id: 15,
        type: "mcq",
        q: "What is the difference between bytesToRead and bytesRead in ReadFile()?",
        opts: [
            "Both indicate whether overlapped I/O is used",
            "They always hold exactly the same value",
            "bytesRead is the requested count; bytesToRead is the count actually read",
            "bytesToRead is the number of bytes requested; bytesRead is the number actually read during the last read",
        ],
        ans: 3,
        why: "You may ask for 100 bytes but only get 40 (e.g., near end of file); bytesRead reports what really happened.",
    },
    {
        id: 16,
        type: "mcq",
        q: "Typically, each system call is associated with a:",
        opts: ["User name", "File name", "Number", "IP address"],
        ans: 2,
        why: "The number identifies which system call is being requested.",
    },
    {
        id: 17,
        type: "mcq",
        q: "What does the system-call interface maintain to find the right system call?",
        opts: [
            "The file system directory",
            "A list of all logged-in users",
            "A table indexed according to the system-call numbers",
            "The program's call stack",
        ],
        ans: 2,
        why: "The number is used as an index into the table to find and invoke the kernel routine.",
    },
    {
        id: 18,
        type: "mcq",
        q: "In the diagram, the open() call passes from:",
        opts: [
            "The network to the kernel",
            "Kernel mode to user mode directly",
            "User mode to kernel mode through the system-call interface",
            "Hardware to the user application",
        ],
        ans: 2,
        why: "The user application calls open(); the system-call interface switches to kernel mode and runs the implementation.",
    },
    {
        id: 19,
        type: "mcq",
        q: "After the kernel implementation of open() finishes, what happens?",
        opts: [
            "printf() is called automatically",
            "The computer restarts",
            "Control returns through the system-call interface with the status and any return values",
            "The kernel halts the application",
        ],
        ans: 2,
        why: 'The "return" arrow in the diagram brings results back to the user application.',
    },
    {
        id: 20,
        type: "mcq",
        q: "Why does the implementation of open() run in kernel mode rather than user mode?",
        opts: [
            "Because open() is part of the GUI",
            "Because code runs faster in user mode",
            "It needs to access protected resources, such as the disk and file-system structures, that only the kernel may touch",
            "Because C code cannot run in user mode",
        ],
        ans: 2,
        why: "Kernel mode is privileged; forcing file access through the kernel protects the system from misbehaving programs.",
    },
    {
        id: 21,
        type: "mcq",
        q: "printf() is:",
        opts: [
            "A kernel function",
            "A library function in the standard C library that runs in user mode",
            "A system call executed in kernel mode",
            "A hardware instruction",
        ],
        ans: 1,
        why: "printf() is in the library (user mode); it relies on the write() system call (kernel mode).",
    },
    {
        id: 22,
        type: "mcq",
        q: "Which is the correct order of events when a program calls printf()?",
        opts: [
            "Program → printf() in C library (user mode) → write() system call (kernel mode) → back to library → back to program",
            "Program → write() in user mode → printf() in kernel mode → program",
            "Kernel → printf() → program → write()",
            "Program → kernel → printf() → hardware, with no system call involved",
        ],
        ans: 0,
        why: "The library sits between the program and the kernel, exactly like the API layer in the previous diagram.",
    },
    {
        id: 23,
        type: "mcq",
        q: "Which method is used by Linux and Solaris?",
        opts: [
            "All parameters are passed in registers only",
            "Parameters are pushed onto the stack only",
            "Parameters are stored in a block (table) in memory, and the block's address is passed in a register",
            "Parameters are placed in global variables",
        ],
        ans: 2,
        why: "Only one register is needed: the one holding the block's address.",
    },
    {
        id: 24,
        type: "mcq",
        q: "Which methods do NOT limit the number or length of parameters being passed?",
        opts: [
            "Registers only",
            "The block (table) method and the stack method",
            "Registers and the stack",
            "Registers and the block method",
        ],
        ans: 1,
        why: "Registers are few, so they limit how many parameters fit; memory blocks and the stack can grow as needed.",
    },
    {
        id: 25,
        type: "mcq",
        q: 'In the diagram, what does "system call 13" refer to?',
        opts: [
            "The number of bytes in the table",
            "The number that identifies which system call is being invoked",
            "The number of parameters passed",
            "The 13th register of the CPU",
        ],
        ans: 1,
        why: "System calls are identified by numbers; here the program requests call number 13.",
    },
    {
        id: 26,
        type: "mcq",
        q: "What is the advantage of passing parameters via a table over passing them all in registers?",
        opts: [
            "It always runs faster than registers",
            "It uses no memory at all",
            "It does not need the kernel",
            "Any number of parameters can be passed using just one register",
        ],
        ans: 3,
        why: "Only the table's address uses a register, so the parameter count is no longer limited by the number of registers.",
    },
    {
        id: 27,
        type: "mcq",
        q: "Which list correctly gives the types of system calls?",
        opts: [
            "Layered, microkernel, modular and virtual machine",
            "Process control, file management, device management, information maintenance, communications",
            "CLI, GUI, batch, API and shell",
            "Booting, SYSGEN, bootstrap and firmware",
        ],
        ans: 1,
        why: "These five categories group all system calls by purpose.",
    },
    {
        id: 28,
        type: "mcq",
        q: "A system call that gets the current time or date belongs to:",
        opts: [
            "Process control",
            "Information maintenance",
            "Communications",
            "Device management",
        ],
        ans: 1,
        why: "Information maintenance calls get or set system data such as time, date and process attributes.",
    },
    {
        id: 29,
        type: "mcq",
        q: "According to the diagram, what happens to the command interpreter when MS-DOS runs a program?",
        opts: [
            "Most of it is overwritten to give the program more memory; only a small part remains and it is reloaded afterward",
            "It is moved entirely to another computer",
            "It stays completely intact in memory",
            "It runs in parallel with the program",
        ],
        ans: 0,
        why: "Compare (a) and (b): the command interpreter area shrinks while the process runs.",
    },
    {
        id: 30,
        type: "mcq",
        q: "Why does MS-DOS not need to create a new process to run a program?",
        opts: [
            "Because it runs many processes at once",
            "Because it uses a microkernel design",
            "Because programs run inside the BIOS",
            "Because it is single-tasking: it loads the program into memory over most of the interpreter and gives it control",
        ],
        ans: 3,
        why: "With only one task at a time, MS-DOS simply loads and jumps to the program; when it exits, the interpreter is reloaded.",
    },
    {
        id: 31,
        type: "mcq",
        q: "What does the FreeBSD memory diagram show?",
        opts: [
            "Several processes (B, C, D) in memory at the same time, along with the interpreter and the kernel",
            "No kernel in memory",
            "Only one process in memory",
            "Only the command interpreter in memory",
        ],
        ans: 0,
        why: "FreeBSD keeps several processes in memory simultaneously.",
    },
    {
        id: 32,
        type: "mcq",
        q: "System programs provide:",
        opts: [
            "Only the kernel code",
            "The physical hardware of the computer",
            "A convenient environment for program development and execution",
            "Only the boot code",
        ],
        ans: 2,
        why: "System programs sit on top of system calls and make the system usable.",
    },
    {
        id: 33,
        type: "mcq",
        q: "Which of the following is NOT one of the system program categories listed?",
        opts: [
            "Status information",
            "Communications",
            "File manipulation",
            "CPU scheduling",
        ],
        ans: 3,
        why: "CPU scheduling is a kernel function, not a system program category.",
    },
    {
        id: 34,
        type: "mcq",
        q: "What is dtrace used for?",
        opts: [
            "Compiling C programs",
            "Booting the operating system",
            "Connecting computers over a network",
            "Tracing system calls and functions as they execute, for debugging and performance analysis",
        ],
        ans: 3,
        why: "dtrace follows the call as it moves through user and kernel code.",
    },
    {
        id: 35,
        type: "mcq",
        q: "In the dtrace output, what do the letters U and K in the last column indicate?",
        opts: [
            "Whether each function executes in user mode (U) or kernel mode (K)",
            "Unknown versus known functions",
            "The user ID and the kernel ID",
            "UNIX versus kernel versions of the function",
        ],
        ans: 0,
        why: "The trace shows the call crossing from user-mode code into kernel-mode code and back.",
    },
    {
        id: 36,
        type: "mcq",
        q: "Some systems implement a registry. What is it used for?",
        opts: [
            "Compiling programs",
            "Loading programs into memory",
            "Sending messages between users",
            "Storing and retrieving configuration information",
        ],
        ans: 3,
        why: "The registry is a status-information facility holding configuration data.",
    },
    {
        id: 37,
        type: "tf",
        q: "All system programs are simply user interfaces to system calls.",
        ans: false,
        why: "False. The slide says some are simple interfaces to system calls, while others are considerably more complex.",
    },
    {
        id: 38,
        type: "mcq",
        q: "Text editors used to create and modify files belong to:",
        opts: [
            "Communications",
            "Status information",
            "File modification",
            "Program loading and execution",
        ],
        ans: 2,
        why: "File modification includes text editors and commands that search or transform file contents.",
    },
    {
        id: 39,
        type: "mcq",
        q: "Which classification is correct?",
        opts: [
            "Remote login and file transfer → file modification",
            "Compilers → status information",
            "Relocatable loaders and linkage editors → program loading and execution",
            "Text editors → communications",
        ],
        ans: 2,
        why: "Remote login / file transfer are communications; editors are file modification; compilers are programming-language support.",
    },
    {
        id: 40,
        type: "mcq",
        q: "Which of these are SYSTEM goals for an operating system?",
        opts: [
            "Convenient to use and easy to learn",
            "Easy to design, implement and maintain, as well as flexible, reliable, error-free and efficient",
            "Fast and safe for end users only",
            "Attractive icons and a friendly GUI",
        ],
        ans: 1,
        why: "System goals are from the point of view of the people who build and maintain the OS.",
    },
    {
        id: 41,
        type: "tf",
        q: 'OS design is a "solved" problem with one correct internal structure that all systems follow.',
        ans: false,
        why: 'False. Design is not "solvable"; internal structures vary widely, though some approaches have proven successful.',
    },
    {
        id: 42,
        type: "mcq",
        q: "Why is separating policy from mechanism an important principle?",
        opts: [
            "It is required by the Win32 API",
            "It makes the hardware faster",
            "It reduces memory usage",
            "It allows maximum flexibility if policy decisions change later",
        ],
        ans: 3,
        why: "A general mechanism can serve many policies, so changing a policy doesn't require rewriting the mechanism.",
    },
    {
        id: 43,
        type: "mcq",
        q: "A timer that interrupts the CPU is a mechanism. Deciding how long the timer is set for a particular user is a:",
        opts: ["Mechanism", "Policy", "Device driver", "System call"],
        ans: 1,
        why: "The timer is how CPU protection is enforced; the time amount is a decision about what to do, i.e., a policy.",
    },
    {
        id: 44,
        type: "mcq",
        q: "What is MS-DOS's main structural weakness?",
        opts: [
            "It is built on top of a virtual machine",
            "It suffers from microkernel message-passing overhead",
            "It has too many independent modules",
            "It is not divided into modules, and its interfaces and levels of functionality are not well separated",
        ],
        ans: 3,
        why: "MS-DOS has some structure, but its parts are tangled together.",
    },
    {
        id: 45,
        type: "mcq",
        q: "Why did MS-DOS end up with this simple structure?",
        opts: [
            "Its designers prioritized packing maximum functionality into the least space on limited hardware",
            "It was built for large multiuser mainframes",
            "It needed to run inside a Java Virtual Machine",
            "It was designed as a microkernel",
        ],
        ans: 0,
        why: "Tight memory limits encouraged a compact but poorly separated design.",
    },
    {
        id: 46,
        type: "mcq",
        q: "According to the diagram, an application program in MS-DOS can:",
        opts: [
            "Access hardware only through a microkernel",
            "Never access any device driver",
            "Only call the resident system program",
            "Skip the middle layers and access the ROM BIOS device drivers directly",
        ],
        ans: 3,
        why: "The arrows from the application go all the way down to the BIOS drivers.",
    },
    {
        id: 47,
        type: "mcq",
        q: "What is the risk of letting applications access the lowest layers directly?",
        opts: [
            "There is no risk at all",
            "It improves portability to new hardware",
            "It makes the system slower but safer",
            "A buggy or malicious program can crash the whole system, because nothing protects the hardware",
        ],
        ans: 3,
        why: "Without protection, one bad program can overwrite or misuse hardware and bring everything down.",
    },
    {
        id: 48,
        type: "mcq",
        q: "In a layered OS, each layer uses:",
        opts: [
            "Only the functions of higher layers",
            "Only the functions of layer N",
            "Only the functions and services of lower-level layers",
            "The functions of any layer, above or below",
        ],
        ans: 2,
        why: "This strict ordering is what gives the layered approach its modularity.",
    },
    {
        id: 49,
        type: "mcq",
        q: "What is the main benefit of the layered approach?",
        opts: [
            "Simpler construction and debugging, since each layer can be tested assuming the lower layers already work",
            "It avoids any need for modularity",
            "No overhead at all when calling services",
            "It lets applications reach hardware directly",
        ],
        ans: 0,
        why: "Debug layer 0 first, then layer 1, and so on; an error found must be in the current layer.",
    },
    {
        id: 50,
        type: "tf",
        q: "In the diagram, layer 1 is built directly on top of the hardware (layer 0).",
        ans: true,
        why: "True. Each ring is built on the ring just inside it.",
    },
    {
        id: 51,
        type: "mcq",
        q: "What is a major disadvantage of the layered approach?",
        opts: [
            "It cannot be debugged at all",
            "It provides no modularity",
            "It gives no access to the hardware",
            "Requests pass through many layers, adding overhead, and defining the layers correctly is difficult",
        ],
        ans: 3,
        why: "Each layer adds a step to a request, and some functions don't fit neatly into a strict order.",
    },
    {
        id: 52,
        type: "mcq",
        q: "Why is the original UNIX considered to have limited structuring?",
        opts: [
            "A large number of functions (file system, CPU scheduling, memory management, …) are combined in one level",
            "It has too many strict layers",
            "It is a microkernel",
            "It runs inside a virtual machine",
        ],
        ans: 0,
        why: "Putting many functions in a single kernel level makes it monolithic: fast, but hard to maintain.",
    },
    {
        id: 53,
        type: "mcq",
        q: "In the UNIX structure diagram, page replacement, demand paging and virtual memory are handled in the:",
        opts: [
            "Kernel",
            "System libraries",
            "Hardware controllers",
            "Shells and commands",
        ],
        ans: 0,
        why: "These memory-management functions are listed inside the kernel box.",
    },
    {
        id: 54,
        type: "mcq",
        q: "The UNIX kernel is bounded above and below by:",
        opts: [
            "The users (above) and the shells (below)",
            "The system-call interface (above) and the kernel interface to the hardware (below)",
            "The GUI (above) and BIOS (below)",
            "The libraries (above) and the system programs (below)",
        ],
        ans: 1,
        why: "The two interfaces define exactly where the kernel begins and ends.",
    },
    {
        id: 55,
        type: "mcq",
        q: "Why is a microkernel system more reliable?",
        opts: [
            "More code runs in kernel mode",
            "Less code runs in kernel mode, so a failing service does not crash the kernel",
            "It has no user space at all",
            "It runs faster than any other design",
        ],
        ans: 1,
        why: "Most services run as user processes; if one fails, the kernel and other services survive.",
    },
    {
        id: 56,
        type: "mcq",
        q: "What is the main detriment of the microkernel approach?",
        opts: [
            "It is hard to port to new architectures",
            "It is hard to extend",
            "Performance overhead of communication between user space and kernel space",
            "It is less secure than a monolithic kernel",
        ],
        ans: 2,
        why: "Every service request becomes messages crossing user/kernel boundaries, which costs time.",
    },
    {
        id: 57,
        type: "mcq",
        q: "Which two components form the Mac OS X kernel environment?",
        opts: [
            "Mach and BSD",
            "Solaris and MS-DOS",
            "JVM and VMware",
            "Linux and Windows NT",
        ],
        ans: 0,
        why: "The diagram shows BSD on top of Mach inside the kernel environment.",
    },
    {
        id: 58,
        type: "mcq",
        q: "How is the Mac OS X structure best described?",
        opts: [
            "A hybrid: the Mach microkernel combined with BSD components in the kernel environment",
            "A pure layered system",
            "A simple structure like MS-DOS",
            "A pure monolithic kernel with no microkernel",
        ],
        ans: 0,
        why: "Mach supplies memory management, IPC and thread scheduling; BSD supplies UNIX services.",
    },
    {
        id: 59,
        type: "mcq",
        q: "In Mac OS X, which component provides the command-line interface, networking, file systems and POSIX APIs?",
        opts: [
            "The hardware",
            "The application environments layer",
            "Mach",
            "BSD",
        ],
        ans: 3,
        why: "BSD adds the UNIX personality on top of Mach's low-level services.",
    },
    {
        id: 60,
        type: "mcq",
        q: "Kernel modules are loadable:",
        opts: [
            "Never after installation",
            "Only in user space",
            "As needed within the kernel",
            "Only when the kernel is compiled",
        ],
        ans: 2,
        why: "Modules can be added to the running kernel when their functionality is needed.",
    },
    {
        id: 61,
        type: "mcq",
        q: "How do modules compare with layers?",
        opts: [
            "Exactly like layers: a module may only call lower modules",
            "Modules are always slower than layers",
            "Modules have no interfaces between them",
            "Similar to layers but more flexible: any module can call any other module over known interfaces",
        ],
        ans: 3,
        why: "Modules keep clean interfaces like layers but drop the strict ordering.",
    },
    {
        id: 62,
        type: "mcq",
        q: "What is an advantage of the Solaris modular approach?",
        opts: [
            "Every module communicates only through slow message passing",
            "New support (e.g., a new file system) is added by loading a module, not rebuilding the kernel, while modules still run efficiently in kernel space",
            "Modules run as separate user processes",
            "The whole kernel must be recompiled for each new feature",
        ],
        ans: 1,
        why: "It combines the flexibility of a microkernel with the speed of in-kernel calls.",
    },
    {
        id: 63,
        type: "mcq",
        q: "A virtual machine provides an interface that is:",
        opts: [
            "A simplified version of the hardware",
            "A network protocol",
            "A graphical user interface",
            "Identical to the underlying bare hardware",
        ],
        ans: 3,
        why: "Each guest OS thinks it is running on a real machine.",
    },
    {
        id: 64,
        type: "mcq",
        q: "How does a virtual machine take the layered approach to its logical conclusion?",
        opts: [
            "It removes all layers from the system",
            "It treats the hardware and the OS kernel together as though they were all hardware",
            "It gives each layer its own physical machine",
            "It moves the kernel into user space",
        ],
        ans: 1,
        why: "To the software above it, the VM layer looks exactly like bare hardware.",
    },
    {
        id: 65,
        type: "mcq",
        q: "Virtual card readers and virtual line printers are provided by:",
        opts: [
            "CPU scheduling",
            "Spooling and a file system",
            "The API",
            "The bootstrap program",
        ],
        ans: 1,
        why: 'Spooling buffers device I/O on disk, so each VM gets its own "device".',
    },
    {
        id: 66,
        type: "mcq",
        q: "In a VM system, what serves as the virtual machine operator's console?",
        opts: [
            "The ROM BIOS",
            "A normal user time-sharing terminal",
            "A dedicated physical console for each VM",
            "The system-call table",
        ],
        ans: 1,
        why: "Each user's regular terminal acts as the console of that user's virtual machine.",
    },
    {
        id: 67,
        type: "mcq",
        q: "What layer sits between the VM kernels and the hardware in diagram (b)?",
        opts: [
            "The programming interface",
            "The BIOS",
            "A command shell",
            "The virtual-machine implementation",
        ],
        ans: 3,
        why: "The VM implementation makes the one real machine look like several.",
    },
    {
        id: 68,
        type: "mcq",
        q: "What is the downside of VM isolation?",
        opts: [
            "It prevents OS research",
            "It permits no direct sharing of resources between VMs",
            "It removes all protection",
            "It makes the CPU slower",
        ],
        ans: 1,
        why: "The same wall that protects VMs also stops them from sharing directly.",
    },
    {
        id: 69,
        type: "mcq",
        q: "Why is a virtual machine a perfect vehicle for OS research and development?",
        opts: [
            "Development is done on the VM, so it does not disrupt normal system operation on the physical machine",
            "Code written on VMs never has bugs",
            "VMs are always faster than real machines",
            "VMs make hardware unnecessary",
        ],
        ans: 0,
        why: "A crash in the experimental OS only brings down its VM, not the real system everyone else uses.",
    },
    {
        id: 70,
        type: "mcq",
        q: "In the VMware diagram, what does each guest OS (FreeBSD, Windows NT, Windows XP) see?",
        opts: [
            "The real hardware directly",
            "A virtual CPU, virtual memory and virtual devices",
            "Nothing; it has no resources",
            "The host kernel's internal code",
        ],
        ans: 1,
        why: "The virtualization layer gives each guest its own virtual hardware.",
    },
    {
        id: 71,
        type: "mcq",
        q: "What is the role of the virtualization layer in VMware?",
        opts: [
            "It is the Java interpreter",
            "It runs inside each guest OS",
            "It is the physical hardware itself",
            "It sits between the guest OSes and the host OS, mapping virtual CPUs, memory and devices onto the real resources",
        ],
        ans: 3,
        why: "Guests make requests to virtual hardware; the virtualization layer turns them into real operations through the host.",
    },
    {
        id: 72,
        type: "mcq",
        q: "Java programs are compiled into:",
        opts: [
            "Assembly code for one CPU",
            "C source code",
            ".exe files for Windows only",
            ".class files, which the class loader loads",
        ],
        ans: 3,
        why: "The JVM diagram shows Java program .class files and Java API .class files feeding the class loader.",
    },
    {
        id: 73,
        type: "mcq",
        q: "Booting means:",
        opts: [
            "Installing application programs",
            "Starting a computer by loading the kernel",
            "Compiling the operating system",
            "Shutting down the computer",
        ],
        ans: 1,
        why: "Booting brings the kernel into memory and starts it.",
    },
    {
        id: 74,
        type: "mcq",
        q: "Why is the bootstrap program stored in ROM?",
        opts: [
            "Because it is too large for disk",
            "Because ROM is the fastest type of memory",
            "It must be available immediately at power-on and must not be lost or altered",
            "Because the cache is too small",
        ],
        ans: 2,
        why: "RAM is empty at power-on, so the first code must live in non-volatile ROM.",
    },
    {
        id: 75,
        type: "mcq",
        q: "The initial boot code is held in:",
        opts: [
            "RAM",
            "Firmware (forms of ROM, e.g., EPROM)",
            "Cache memory",
            "CPU registers",
        ],
        ans: 1,
        why: "Firmware keeps the boot code even when the power is off.",
    },
    {
        id: 76,
        type: "mcq",
        q: "When power is initialized on the system, execution starts:",
        opts: [
            "At a random memory location",
            "At the user's program",
            "At a fixed memory location",
            "At the kernel stored on disk",
        ],
        ans: 2,
        why: "The CPU always begins at the same known address, where the boot code lives.",
    },
];
