const QUESTIONS = [
    {
        id: 1,
        type: "mcq",
        q: "Which part of a process holds global variables?",
        opts: ["Stack", "Heap", "Program counter", "Data section"],
        ans: 3,
        why: "The data section holds globals; the stack holds temporary data (parameters, return addresses, locals).",
    },
    {
        id: 2,
        type: "mcq",
        q: "Which region of a process in memory is dynamically allocated during run time?",
        opts: ["Text", "Heap", "Program counter", "Data"],
        ans: 1,
        why: 'The diagram labels the heap as "dynamically allocated during process run time".',
    },
    {
        id: 3,
        type: "essay",
        q: "The program code of a process is stored in the ______ section.",
        ans: "text",
        why: "The text section (at the bottom, address 0) holds the program code.",
    },
    {
        id: 4,
        type: "mcq",
        q: "In the process memory diagram, where is the stack located?",
        opts: [
            "Bottom (near address 0)",
            "Top (near max address)",
            "Just above the text section",
            "Just above the data section",
        ],
        ans: 1,
        why: "From top to bottom: stack → free space → heap → data → text.",
    },
    {
        id: 5,
        type: "mcq",
        q: "A process whose instructions are currently being executed is in which state?",
        opts: ["New", "Waiting", "Ready", "Running"],
        ans: 3,
        why: "Running means the CPU is executing its instructions right now.",
    },
    {
        id: 6,
        type: "essay",
        q: "A process that has finished execution is in the ______ state.",
        ans: "terminated",
        why: "The five states are new, running, waiting, ready and terminated.",
    },
    {
        id: 7,
        type: "mcq",
        q: "Which transition happens when an interrupt occurs while a process is running?",
        opts: [
            "Ready → Terminated",
            "Running → Waiting",
            "Running → Ready",
            "Waiting → Ready",
        ],
        ans: 2,
        why: "An interrupt takes the CPU away, but the process can still run, so it returns to ready.",
    },
    {
        id: 8,
        type: "mcq",
        q: "In the process state diagram, which transition is caused by the “Admitted” event?",
        opts: [
            "Running → Waiting",
            "Waiting → Ready",
            "Running → Terminated",
            "New → Ready",
        ],
        ans: 3,
        why: "Admitted moves a new process into the ready state; the other arrows are labeled I/O or event wait, I/O or event completion, and exit.",
    },
    {
        id: 9,
        type: "mcq",
        q: 'In the PCB, "the amount of CPU and real time used" belongs to which kind of information?',
        opts: [
            "I/O status information",
            "CPU scheduling information",
            "Accounting information",
            "Memory-management information",
        ],
        ans: 2,
        why: "Accounting information records resource usage such as CPU time and real time.",
    },
    {
        id: 10,
        type: "mcq",
        q: "What does the PCB field “CPU registers” store?",
        opts: [
            "General-purpose registers, stack pointer",
            "Amount of CPU and real time used",
            "Address of the next instruction",
            "Pointer to the scheduling queue",
        ],
        ans: 0,
        why: "CPU registers hold the register contents (including the stack pointer) that must be saved and restored so the process can resume.",
    },
    {
        id: 11,
        type: "mcq",
        q: "Which field in the PCB diagram uniquely identifies the process?",
        opts: [
            "Program counter",
            "Memory limits",
            "Registers",
            "Process number",
        ],
        ans: 3,
        why: "The process number (process ID) distinguishes each process.",
    },
    {
        id: 12,
        type: "mcq",
        q: "When switching from P0 to P1, what does the operating system do first?",
        opts: [
            "Create a new PCB for P1",
            "Terminate P0",
            "Save the state of P0 into PCB0",
            "Reload the state of P1 from PCB1",
        ],
        ans: 2,
        why: "The OS first saves the old process's state, then reloads the next process's state.",
    },
    {
        id: 13,
        type: "mcq",
        q: "The set of processes residing in main memory, ready and waiting to execute, is the:",
        opts: ["Ready queue", "Job queue", "Device queue", "Waiting queue"],
        ans: 0,
        why: "The ready queue holds processes in memory that are ready to run.",
    },
    {
        id: 14,
        type: "mcq",
        q: "What is linked together to form the ready queue in the diagram?",
        opts: [
            "Process Control Blocks (PCBs)",
            "Memory pages",
            "Device drivers",
            "Program counters only",
        ],
        ans: 0,
        why: "Queues are implemented as linked lists of PCBs.",
    },
    {
        id: 15,
        type: "mcq",
        q: "In the queue diagram, which processes wait in the ready queue?",
        opts: [
            "Processes waiting for the disk",
            "Processes waiting for the terminal",
            "Processes waiting for the CPU",
            "Processes waiting for the magnetic tape",
        ],
        ans: 2,
        why: "The ready queue holds processes waiting for the CPU; every device also has its own queue.",
    },
    {
        id: 16,
        type: "mcq",
        q: "According to the diagram, what happens after a process issues an I/O request?",
        opts: [
            "It is placed in an I/O queue until the I/O completes",
            "It stays on the CPU",
            "It is terminated immediately",
            "It forks a child process",
        ],
        ans: 0,
        why: "An I/O request sends the process to an I/O queue; after I/O it returns to the ready queue.",
    },
    {
        id: 17,
        type: "mcq",
        q: "In the queueing diagram, where does a process go after it issues an I/O request?",
        opts: [
            "Ready queue",
            "CPU",
            "I/O queue",
            "It waits until the interrupt occurs",
        ],
        ans: 2,
        why: "An I/O request sends the process to an I/O queue; after the I/O completes it returns to the ready queue.",
    },
    {
        id: 18,
        type: "mcq",
        q: "Which scheduler selects which processes should be brought into the ready queue?",
        opts: [
            "Short-term scheduler",
            "Long-term scheduler",
            "Medium-term scheduler",
            "Dispatcher",
        ],
        ans: 1,
        why: "The long-term (job) scheduler admits processes into memory and the ready queue.",
    },
    {
        id: 19,
        type: "mcq",
        q: "What is the scheme used by the medium-term scheduler called?",
        opts: ["Spooling", "Forking", "Paging", "Swapping"],
        ans: 3,
        why: "Partially executed processes are swapped out of memory and later swapped back in.",
    },
    {
        id: 20,
        type: "mcq",
        q: "In medium-term scheduling, what does “swap out” mean?",
        opts: [
            "Move a process from memory to disk",
            "Bring a swapped-out process back into memory",
            "Terminate the process and release its PCB",
            "Move a process from the ready queue to the CPU",
        ],
        ans: 0,
        why: "Swap out moves a process from memory to disk; swap in later brings it back to continue execution.",
    },
    {
        id: 21,
        type: "mcq",
        q: "Which scheduler controls the degree of multiprogramming?",
        opts: [
            "Interrupt handler",
            "Long-term scheduler",
            "Dispatcher",
            "Short-term scheduler",
        ],
        ans: 1,
        why: "Deciding how many processes enter memory controls the degree of multiprogramming.",
    },
    {
        id: 22,
        type: "mcq",
        q: "Which description applies to the short-term scheduler?",
        opts: [
            "Invoked in seconds or minutes; may be slow",
            "Spends more time on computations",
            "A mix of CPU-bound and I/O-bound processes",
            "Invoked in milliseconds; must be fast",
        ],
        ans: 3,
        why: "The short-term scheduler runs very often, so it must be fast; the long-term scheduler runs rarely and may be slow.",
    },
    {
        id: 23,
        type: "mcq",
        q: "Context-switch time depends heavily on:",
        opts: [
            "The screen resolution",
            "The number of users logged in",
            "The size of the hard disk",
            "Hardware support, such as memory speed and the number of registers to copy",
        ],
        ans: 3,
        why: "Faster memory and fewer registers to save and load mean faster switches.",
    },
    {
        id: 24,
        type: "mcq",
        q: "Which is NOT a resource-sharing option between a parent and its children?",
        opts: [
            "Children own all resources and the parent owns none",
            "Parent and child share no resources",
            "Children share a subset of the parent's resources",
            "Parent and children share all resources",
        ],
        ans: 0,
        why: "The slide lists: share all, share a subset, or share nothing.",
    },
    {
        id: 25,
        type: "mcq",
        q: "In process creation, which category does the option “children share a subset of the parent’s resources” belong to?",
        opts: [
            "Execution",
            "Resource sharing",
            "Address space",
            "Process termination",
        ],
        ans: 1,
        why: "The options are grouped into resource sharing (all, a subset, or none of the resources) and execution (concurrent or parent waits).",
    },
    {
        id: 26,
        type: "mcq",
        q: "In UNIX, which system call creates a new process?",
        opts: ["exit", "fork", "exec", "wait"],
        ans: 1,
        why: "fork() creates the child as a duplicate of the parent.",
    },
    {
        id: 27,
        type: "mcq",
        q: "What does the UNIX call fork do?",
        opts: [
            "Creates a new process",
            "Replaces the process’s memory with a new program",
            "Makes the parent wait for a child to finish",
            "Terminates the calling process",
        ],
        ans: 0,
        why: "fork creates a new process; exec then loads a program and wait lets the parent wait for the child.",
    },
    {
        id: 28,
        type: "mcq",
        q: "In the process creation diagram, what does the child do after fork()?",
        opts: [
            "Calls wait()",
            "Resumes the parent",
            "Calls exec()",
            "Creates the parent",
        ],
        ans: 2,
        why: "The child path is fork() → exec() → exit().",
    },
    {
        id: 29,
        type: "mcq",
        q: "In the process creation diagram, who performs the wait() call?",
        opts: ["Child", "Both parent and child", "Parent", "The scheduler"],
        ans: 2,
        why: "The parent forks the child and then calls wait() until the child finishes; the child execs a program and exits.",
    },
    {
        id: 30,
        type: "mcq",
        q: "What does the child process run in this program?",
        opts: [
            "Another fork()",
            'The ls command, through execlp("/bin/ls", "ls", NULL)',
            "wait(NULL)",
            'printf("Child Complete")',
        ],
        ans: 1,
        why: "The child replaces itself with the ls program using execlp().",
    },
    {
        id: 31,
        type: "mcq",
        q: "What does a fork() return value of pid < 0 mean?",
        opts: [
            "This is the child process",
            "Fork failed (error)",
            "This is the parent process",
            "The child has already terminated",
        ],
        ans: 1,
        why: "A negative value means the fork failed; 0 identifies the child and a positive value identifies the parent.",
    },
    {
        id: 32,
        type: "mcq",
        q: "In the Solaris tree, which process is the parent of all user processes?",
        opts: [
            "init (pid = 1)",
            "pageout (pid = 2)",
            "fsflush (pid = 3)",
            "ls",
        ],
        ans: 0,
        why: "init (pid 1) is the ancestor of user processes such as logins and shells.",
    },
    {
        id: 33,
        type: "mcq",
        q: "Which is NOT a reason for a parent to abort a child process?",
        opts: [
            "The child has finished its last statement normally",
            "The task assigned to the child is no longer required",
            "The child has exceeded its allocated resources",
            "The parent is exiting",
        ],
        ans: 0,
        why: "Finishing normally is exit, not abort.",
    },
    {
        id: 34,
        type: "mcq",
        q: "In process termination, what does exit do?",
        opts: [
            "Parent receives output data from the child",
            "Parent terminates a child",
            "All children end when the parent ends",
            "Process asks the OS to delete it",
        ],
        ans: 3,
        why: "exit is how a process asks the OS to delete it; wait, abort and cascading termination are the other ideas on the slide.",
    },
    {
        id: 35,
        type: "mcq",
        q: "Which of these is NOT listed as an advantage of process cooperation?",
        opts: [
            "Computation speed-up",
            "Information sharing",
            "Modularity",
            "Reduced memory usage",
        ],
        ans: 3,
        why: "The four advantages are information sharing, computation speed-up, modularity and convenience.",
    },
    {
        id: 36,
        type: "mcq",
        q: "In the producer-consumer problem, what is an unbounded buffer?",
        opts: [
            "Fixed buffer size",
            "First full position in the buffer",
            "Next free position in the buffer",
            "No practical limit on the buffer size",
        ],
        ans: 3,
        why: "An unbounded buffer has no practical limit; a bounded buffer has a fixed size. The producer writes at in and the consumer reads at out.",
    },
    {
        id: 37,
        type: "mcq",
        q: "Why can the solution use only BUFFER_SIZE − 1 elements?",
        opts: [
            "One slot is reserved for the operating system",
            "One slot is left empty so that a full buffer can be distinguished from an empty one",
            "The last slot is used for the in variable",
            "Arrays in C cannot use their last element",
        ],
        ans: 1,
        why: "If all slots were used, a full buffer would also give in == out, which looks empty.",
    },
    {
        id: 38,
        type: "mcq",
        q: "After placing an item in buffer[in], how is in updated?",
        opts: [
            "in = (in + 1) % BUFFER_SIZE",
            "in = out",
            "in = 0",
            "in = in + 1",
        ],
        ans: 0,
        why: "The modulo wraps in back to 0, making the buffer circular.",
    },
    {
        id: 39,
        type: "mcq",
        q: "In insert(), what is the purpose of the line while (((in + 1) % BUFFER_SIZE) == out);?",
        opts: [
            "Store the new item",
            "Wait while the buffer is full",
            "Advance to the next slot circularly",
            "Remove an item from the buffer",
        ],
        ans: 1,
        why: "This line loops while the buffer is full. The order is: check for space → store the item → advance in.",
    },
    {
        id: 40,
        type: "mcq",
        q: "After taking buffer[out], how is out updated?",
        opts: [
            "out = 0",
            "out = (out + 1) % BUFFER_SIZE",
            "out = out − 1",
            "out = in",
        ],
        ans: 1,
        why: "Like in, out wraps around circularly.",
    },
    {
        id: 41,
        type: "mcq",
        q: "For IPC link implementation, what is an example of a physical link?",
        opts: [
            "Defined by logical properties",
            "Message size fixed or variable",
            "Shared memory or a hardware bus",
            "A mailbox identified by a unique id",
        ],
        ans: 2,
        why: "A link can be implemented physically (shared memory, hardware bus) or logically (defined by its logical properties).",
    },
    {
        id: 42,
        type: "mcq",
        q: "Which of these is one of the implementation questions on the slide?",
        opts: [
            "What is the capacity of a link?",
            "Which GUI is used?",
            "What is the CPU clock speed?",
            "How large is the hard disk?",
        ],
        ans: 0,
        why: "Questions cover link establishment, number of processes, number of links, capacity, message size and direction.",
    },
    {
        id: 43,
        type: "mcq",
        q: "In the message-passing model (a), messages pass through:",
        opts: [
            "The user's keyboard",
            "The hardware directly",
            "The kernel",
            "A shared memory region only",
        ],
        ans: 2,
        why: "Process A sends M to the kernel, and the kernel delivers it to process B.",
    },
    {
        id: 44,
        type: "mcq",
        q: "In direct communication, send(P, message) means:",
        opts: [
            "Send a message to process P",
            "Receive a message from process P",
            "Create a mailbox named P",
            "Send a message to mailbox P",
        ],
        ans: 0,
        why: "Processes must name each other explicitly.",
    },
    {
        id: 45,
        type: "mcq",
        q: "When can two processes communicate using indirect communication?",
        opts: [
            "Only if one is the parent of the other",
            "Only if they share a mailbox",
            "Only if they are on the same machine",
            "Only if they name each other explicitly",
        ],
        ans: 1,
        why: "The link exists only when processes share a common mailbox.",
    },
    {
        id: 46,
        type: "mcq",
        q: "Which communication type has exactly one link between each pair of processes?",
        opts: [
            "Direct communication",
            "Indirect communication",
            "Both direct and indirect communication",
            "Neither direct nor indirect communication",
        ],
        ans: 0,
        why: "Direct communication has exactly one link per pair, while indirect communication may have several links through mailboxes.",
    },
    {
        id: 47,
        type: "mcq",
        q: "What does send(A, message) do?",
        opts: [
            "Sends a message to mailbox A",
            "Destroys mailbox A",
            "Creates mailbox A",
            "Sends a message to process A",
        ],
        ans: 0,
        why: "In indirect communication, A names a mailbox, not a process.",
    },
    {
        id: 48,
        type: "essay",
        q: "receive(A, message) receives a message from ______ A.",
        ans: "mailbox",
        why: "The primitive names the mailbox, not the sender.",
    },
    {
        id: 49,
        type: "mcq",
        q: 'Which is one of the solutions to "who gets the message?"',
        opts: [
            "Delete the message",
            "Allow only one process at a time to execute a receive operation",
            "Deliver the message to every process",
            "Let the sender wait forever",
        ],
        ans: 1,
        why: "The three solutions: at most two processes per link, one receiver at a time, or arbitrary selection.",
    },
    {
        id: 50,
        type: "mcq",
        q: "With a non-blocking receive, the receiver gets:",
        opts: [
            "Nothing until a message arrives",
            "Either a valid message or null",
            "All messages at once",
            "An error every time",
        ],
        ans: 1,
        why: "Non-blocking receive never waits; it returns null if no message is available.",
    },
    {
        id: 51,
        type: "mcq",
        q: "What does a blocking send do?",
        opts: [
            "Receiver waits until a message is available",
            "Sender waits until the message is received",
            "Sender sends and continues",
            "Gets a valid message or null",
        ],
        ans: 1,
        why: "Blocking send is synchronous: the sender waits until the message is received. Non-blocking send lets the sender continue.",
    },
    {
        id: 52,
        type: "mcq",
        q: "With zero-capacity buffering:",
        opts: [
            "Messages are discarded",
            "The sender never waits",
            "The sender waits only if n messages are queued",
            "The sender must wait for the receiver (rendezvous)",
        ],
        ans: 3,
        why: "With no queue, each message must be handed over directly.",
    },
    {
        id: 53,
        type: "mcq",
        q: "With zero-capacity buffering, how does the sender behave?",
        opts: [
            "Sender waits only if the link is full",
            "Sender never waits",
            "Receiver never waits",
            "Sender waits for receiver (rendezvous)",
        ],
        ans: 3,
        why: "With zero capacity the queue holds no messages, so the sender must wait for the receiver (rendezvous).",
    },
    {
        id: 54,
        type: "mcq",
        q: "Which of these is NOT listed as a client-server communication method?",
        opts: [
            "Remote Procedure Calls",
            "Remote Method Invocation",
            "Shared-memory buffers",
            "Sockets",
        ],
        ans: 2,
        why: "The three listed methods are sockets, RPC and RMI.",
    },
    {
        id: 55,
        type: "mcq",
        q: "The socket 161.25.19.8:1625 refers to:",
        opts: [
            "Mailbox 1625",
            "Process 1625 on the local machine",
            "Port 1625 on host 161.25.19.8",
            "Host 1625 on port 161.25.19.8",
        ],
        ans: 2,
        why: "The part before the colon is the IP address; after it is the port.",
    },
    {
        id: 56,
        type: "mcq",
        q: "What does the server-side stub do?",
        opts: [
            "Sends the result to a mailbox",
            "Locates the server",
            "Creates a new socket for the client",
            "Receives the message, unpacks the marshalled parameters and performs the procedure on the server",
        ],
        ans: 3,
        why: "The server stub reverses what the client stub did, then runs the procedure.",
    },
    {
        id: 57,
        type: "mcq",
        q: "What does the client kernel do first to find the RPC server's port?",
        opts: [
            "Sends the RPC directly to port 80",
            "Forks the server",
            "Sends a message to the matchmaker asking for the port number",
            "Creates a mailbox",
        ],
        ans: 2,
        why: "The client asks the matchmaker which port serves procedure X.",
    },
];
